feat!: refactor contract calls and multicall to JS + fuel-asm
FuelLabs/fuels-ts pull request #1164
Opened 2023-08-06 18:29 UTC by camsjams

This PR converts the Sway file to asm, allowing for:
- a contract call script that doesn't require a Sway compile step
- easier upgrades
- smaller payload size for contract calls
- unlimited mulitcalls (currently 5 maximum)
- IMO the most important changes to look at are all within `packages/program/src/contract-call-script.ts`

### Notes:
- Uses fuel-asm-wasm from @xgreenx and @arboleya (thanks :tada: )
- Added basic wrapper for fuel-asm for DX ergonomics
- removes all usage and sources of multicall Sway contract
- added tests for multicalls greater than 5 now :rocket: 
- **10 file changes are just deletions**, many are just adjusting unit tests :+1: 
- reducing the size of the contract call script changed the gas required

2023-08-07 21:58 UTC, Dhaiwat10 submitted a review, later dismissed
Super clean 💯

2023-08-07 21:58 UTC, Dhaiwat10 commented on packages/providers/src/transaction-request/script-transaction-request.ts
> +    this.script = script.bytes;
Any reason for this change in order? 😅

2023-08-07 21:58 UTC, Dhaiwat10 commented on packages/program/src/contract-call-script.ts
> +};
```suggestion
const DEFAULT_OPCODE_PARAMS: CallOpcodeParamsOffset = {
  assetIdOffset: 0,
  amountOffset: 0,
  gasForwardedOffset: 0,
  callDataOffset: 0,
};
```
A small type annotation

2023-08-08 15:42 UTC, Dhaiwat10 submitted a review, later dismissed

2023-08-11 11:49 UTC, Torres-ssf submitted a review, later dismissed

2023-08-11 13:20 UTC, Dhaiwat10 commented
@camsjams Looks like there are some merge conflicts that need to be resolved before this can be merged.

2023-08-12 09:49 UTC, arboleya requested changes
Can we use the [last version](https://www.npmjs.com/package/@fuels/vm-asm) of `@fuels/vm-asm`?

Version `0.36.0` includes that last fix to enforce [async initialization](https://github.com/FuelLabs/fuel-vm/pull/534):

```ts
import * as fuel_asm from '@fuels/vm-asm'

(async function() {
  await fuel_asm.initWasm();

  // fuel_asm.<?>();
  // ...
})();
```

2023-08-12 12:06 UTC, arboleya approved these changes
⚡

2023-08-12 12:07 UTC, Dhaiwat10 approved these changes

2023-08-12 12:07 UTC, merged