build: build and cache all forc projects
FuelLabs/fuels-ts pull request #1169
Opened 2023-08-07 13:51 UTC by nedsalk

2023-08-10 08:59 UTC, danielbate reviewed
Couple comments, the script and approach seems good to me if something like this is not already built in.

2023-08-10 08:59 UTC, danielbate commented on package.json
> +    "prpa": "eslint . --ext .ts",
What does `prpa` mean?

2023-08-10 08:59 UTC, danielbate commented on package.json
> +    "build-forc-projects": "./scripts/build-script/build-all-with-cache.sh",
```suggestion
    "build:forc": "./scripts/build-script/build-all-with-cache.sh",
```
We tend to use the `build:some-thing` notation more consistently in the SDK.

2023-08-10 08:59 UTC, danielbate commented on .gitignore
> +#CACHE
```suggestion
# Cache
```
Nit, sorry

2023-08-10 16:16 UTC, arboleya requested changes
I can't see why we'd want to re-implement a hand-made cache solution in Shell Script, considering TurboRepo has it built-in and is already caching our dev pipelines.

We want to avoid building the Forc projects during the `dev` command. Looking at the most straightforward implementation with the least amount of friction added, we should preserve things as they were, segregated per packages, with scripts explicitly set in their `package.json` in an obvious manner.

Some things that come to mind:
 1. Try standardizing all script names — for example, `build:forc` as @danielbate suggested
 2. Call it from a `pretest` step for relevant projects
     - `"pretest": "pnpm build:forc"`
 3. Review and adjust any TurboRepo configs/pipelines to match the goal
 4. Ensure there's no relationship between `forc:build` _(and `pretest`)_, `build`, and `dev`.
 5. Normalize exception for the `fuel-gauge` project _(currently skipped in `build` script)_, making it behave like the others.

2023-08-15 15:45 UTC, nedsalk commented on package.json
> +    "dev": "nodemon --config nodemon.config.json -x 'pnpm build --filter=!fuel-gauge'",
It doesn't affect it and I wanted `pnpm build` to encapsulate `turbo run build` as well as building the forc projects.

2023-08-30 22:56 UTC, arboleya commented
@nedsalk Are you still going to address #1095 issue in this PR, or will you create a new one?

2023-08-31 05:57 UTC, nedsalk commented
@arboleya This is the PR for it, but it's currently on hold.

2023-08-31 10:27 UTC, arboleya commented
Precisely, I'm asking because the last commit is 2x weeks old.

Can we help you with something to get it finished?

2023-09-03 22:47 UTC, nedsalk commented
> Can we help you with something to get it finished?

Thanks @arboleya! Sorry for not answering for so long, but I first wanted to gather my thoughts on it before I can comment any further.

After going through what [you've mentioned](https://github.com/FuelLabs/fuels-ts/pull/1169#pullrequestreview-1572278032), I remembered that I already tested the caching capabilities of turbo and this was/is what I noticed:
1. Turbo indeed caches forc builds,
2. Turbo rebuilds forc projects even when a non-sway file is changed

The reason why I went down this route was to avoid building sway projects when a non-sway file changes. This was primarily driven by not wanting to rebuild the `call-test-script` in the `script` package every time I change anything that's in the dependency chain below `script`, as that sway project rebuilding was being run via a `build` script. I figured that I could easily expand the solution to include all forc projects.

However, after #1164 got merged, there is indeed no need at all to build forc projects in `build` scripts. I tried out your 
> 4. Ensure there's no relationship between forc:build (and pretest), build, and dev.

proposal in a separate branch and it works - it gets cached, with the caveat that turbo rebuilds forc projects even when a non-sway file is changed. But, given that it's a `pretest` step, it's not really that impactful on the dev workflow given that the `pretest` scripts are primarily run during `pnpm ci:test`, which runs the full test suite anyways.

I'll close this PR in favor of #1235 which is in the spirit of your comment.

2023-09-03 22:47 UTC, closed without merging