refactor: use `simulate` instead of `get` on `BaseInvocationScope` class
FuelLabs/fuels-ts pull request #1179
Opened 2023-08-09 16:04 UTC by Torres-ssf

Follow-up from https://github.com/FuelLabs/fuels-ts/issues/1093

2023-08-09 17:58 UTC, danielbate submitted a review, later dismissed
:shipit:

2023-08-10 15:54 UTC, arboleya requested changes
Small nits. Feel free to accept them selectively.

2023-08-10 15:54 UTC, arboleya commented on apps/docs/src/guide/contracts/simulate-transactions.md
> +Simulating a transaction is a powerful feature that allows you to validate whether a given transaction meets its requirements without actually modifying the blockchain. It's a safe way to ensure that
```suggestion
Simulating a transaction is a powerful feature that allows you to validate whether a given transaction meets its requirements without modifying the blockchain. It's a safe way to ensure that a transaction will behave as expected without spending any real resources.
```

2023-08-10 15:54 UTC, arboleya commented on apps/docs/src/guide/contracts/simulate-transactions.md
> +When interacting with a contract, you might want to execute a method that does not change the state of the blockchain. For example, reading a value from storage without modifying it.
```suggestion
When interacting with a contract, you might want to execute a method that does not change the state of the blockchain—for example, reading a value from storage without modifying it.
```

2023-08-10 15:54 UTC, arboleya commented on apps/docs/src/guide/contracts/simulate-transactions.md
> +Using `simulate()` for read-only calls or to test transactions provides a way to safely and efficiently access information from the blockchain or validate how a transaction would behave. It ensures t
```suggestion
Using `simulate()` for read-only calls or to test transactions provides a way to safely and efficiently access information from the blockchain or validate how a transaction would behave. It ensures that no changes will be made to the blockchain and no resources will be spent, making it a valuable tool for data retrieval and development.
```

2023-08-10 15:54 UTC, arboleya commented on apps/docs/src/guide/contracts/simulate-transactions.md
> +`simulate()`: Suitable for both read-only calls and testing transactions that could modify the blockchain's state, this method allows you to safely validate how functions will behave without actually
```suggestion
`simulate()`: Suitable for both read-only calls and testing transactions that could modify the blockchain's state, this method allows you to safely validate how functions will behave without making changes. It's a robust validation, development, and data retrieval utility method, providing confidence in your transactions and interactions with the blockchain.
```

2023-08-10 15:54 UTC, arboleya commented on apps/docs/src/guide/contracts/simulate-transactions.md
> +`call()`: Use this method when calling a function that modifies the blockchain's state, such as transferring funds or updating values. Keep in mind that if you use `call()` on a contract method that
```suggestion
`call()`: Use this method when calling a function that modifies the blockchain's state, such as transferring funds or updating values. Remember that if you use `call()` on a contract method that changes the blockchain state, it _**will**_ spend your resources.
```

2023-08-10 15:54 UTC, arboleya commented on apps/docs/src/guide/contracts/simulate-transactions.md
> +It is worth noting that while `call()` can be used to execute read-only contract methods without spending resources, it's recommended to use `simulate()` for such calls. Using `simulate()` provides a
```suggestion
It is worth noting that while `call()` can be used to execute read-only contract methods without spending resources, it's recommended to use `simulate()` for such calls. Using `simulate()` guarantees that no resources will be spent even if you accidentally execute a contract method that would typically change the blockchain. This additional safeguard makes `simulate()` preferable for read-only interactions.
```

2023-08-10 15:54 UTC, arboleya commented on apps/docs/src/guide/contracts/simulate-transactions.md
> +> **Note:** Even though a `simulate()` call won't modify the blockchain's state and does not spent resources, the transaction must still meet its requirements to be considered valid.
```suggestion
> **Note:** Although a `simulate()` call won't modify the blockchain's state and does not spend resources, the transaction must still meet its requirements to be considered valid.
```

2023-08-11 12:50 UTC, arboleya approved these changes

2023-08-11 13:16 UTC, Dhaiwat10 approved these changes

2023-08-11 13:27 UTC, merged