fix: remove verbose log
FuelLabs/fuels-ts pull request #1323
Opened 2023-10-07 04:24 UTC by camsjams

Fixes #1322

2023-10-09 08:13 UTC, danielbate approved these changes

2023-10-09 08:41 UTC, nedsalk requested changes
IMO it should be noisy so that the user updates their package to the latest version, even if it's a patch version. Sorry, but I'll block this until @digorithm gives his thoughts, because this PR removes patch mismatch warnings altogether.

In the meantime, could you share with us the noisy logs and how they look?

2023-10-09 11:21 UTC, Torres-ssf approved these changes

2023-10-09 19:11 UTC, digorithm commented
> IMO it should be noisy so that the user updates their package to the latest version, even if it's a patch version. Sorry, but I'll block this until @digorithm gives his thoughts, because this PR removes patch mismatch warnings altogether.
> 
> In the meantime, could you share with us the noisy logs and how they look?

Thanks @nedsalk, this is a thoughtful remark. However, patch versions in all repos maintained by Fuel Labs are supposed to be backward compatible, meaning: no breaking changes whatsoever. So a change from `0.x.1` to `0.x.2` should never cause any issue. Given that that's a thing, it doesn't make much sense for us to be noisy about it.

2023-10-09 19:11 UTC, digorithm approved these changes

2023-10-09 20:28 UTC, arboleya approved these changes

2023-10-10 06:50 UTC, nedsalk approved these changes

2023-10-10 08:01 UTC, merged