fix: rearrange provider tx param error code checks
FuelLabs/fuels-ts pull request #1352
Opened 2023-10-16 16:48 UTC by danielbate

Closes #1349

2023-10-17 01:15 UTC, arboleya approved these changes
How come you added a new test, and the overall coverage decreased?

I'm assuming this is an inaccurate report from the CI action.

2023-10-17 01:18 UTC, arboleya requested changes
I found the reason for the coverage decrease.

2023-10-17 01:18 UTC, arboleya commented on packages/providers/test/provider.test.ts
> +  it.only('throws when gas price is lower than min tx gas price', async () => {
```suggestion
  it('throws when gas price is lower than min tx gas price', async () => {
```

2023-10-17 14:28 UTC, danielbate commented on packages/providers/test/provider.test.ts
> +  it.only('throws when gas price is lower than min tx gas price', async () => {
Doh

2023-10-17 14:50 UTC, arboleya requested changes

2023-10-18 16:13 UTC, arboleya approved these changes

2023-10-18 21:49 UTC, digorithm approved these changes

2023-10-18 21:49 UTC, merged