Update packages/abi-typegen/README.md - Fix broken link for Sway types
FuelLabs/fuels-ts pull request #1423
Opened 2023-11-09 13:19 UTC by MartinKong1990

Old: https://fuellabs.github.io/sway/latest/basics/index.html

New: https://fuellabs.github.io/sway/v0.47.0/book/basics/built_in_types.html

2023-11-09 13:57 UTC, arboleya requested changes
Thank you.

2023-11-09 13:57 UTC, arboleya commented on packages/abi-typegen/README.md
> +> For more info on Sway types, click [here](https://fuellabs.github.io/sway/v0.47.0/book/basics/built_in_types.html)
```suggestion
> For more info on Sway types, click [here](https://docs.fuel.network/docs/sway/basics/built_in_types/)
```

2023-11-09 14:07 UTC, arboleya commented
@MartinKong1990 FYI — in case you didn't see the edit on my [last comment](https://github.com/FuelLabs/fuels-ts/pull/1423#pullrequestreview-1722601846).

2023-11-09 14:21 UTC, MartinKong1990 commented
> @MartinKong1990 FYI — in case you didn't see the edit on my [last comment](https://github.com/FuelLabs/fuels-ts/pull/1423#pullrequestreview-1722601846).

Looks like need to install some software in my laptop for pnpm to generate an empty changeset. Any alternative solution?

2023-11-09 14:25 UTC, arboleya commented
What do you mean by "additional software"?

It should be as easy as:
 
```bash
cd fuels-ts
pnpm install
pnpm changeset add --empty
```

Then `add`, `commit` and `push` the generated file.

Voilà.

2023-11-09 15:06 UTC, MartinKong1990 commented
Does resubmit pull request from different branch will solve the changeset problem?

2023-11-10 09:32 UTC, danielbate commented
@MartinKong1990 No, the changeset is an additional file that needs to be added to all PRs, generated using the commands that @arboleya has referenced above. For this PR, we would be expecting an empty changeset, [such as in this example](https://github.com/FuelLabs/fuels-ts/pull/1422/files#diff-4780fec66cc2bb30fc9750aa35df80a80c80ae4003ca13a9d33f2062e1ef0597).

2023-11-10 11:53 UTC, MartinKong1990 commented
> @MartinKong1990 No, the changeset is an additional file that needs to be added to all PRs, generated using the commands that @arboleya has referenced above. For this PR, we would be expecting an empty changeset, [such as in this example](https://github.com/FuelLabs/fuels-ts/pull/1422/files#diff-4780fec66cc2bb30fc9750aa35df80a80c80ae4003ca13a9d33f2062e1ef0597).

@danielbate @arboleya 

Actually I use github.com web site with Windows/Chrome. No luck trying with Windows 10 and ubuntu after install different software. I suggest two possible solutions:

Solution 1: In github.com web site, I create an empty file that same as [.changeset/proud-ducks-travel.md](https://github.com/FuelLabs/fuels-ts/pull/1422/files#diff-4780fec66cc2bb30fc9750aa35df80a80c80ae4003ca13a9d33f2062e1ef0597).  with different name at my fork and push here. 

Solution 2: Close this PR. You guys submit the PR and add me as a co-author.

2023-11-10 12:00 UTC, arboleya commented
Option 1.

2023-11-10 12:21 UTC, Dhaiwat10 approved these changes

2023-11-10 12:30 UTC, arboleya approved these changes
Thank you.

2023-11-10 12:39 UTC, merged