Improve the documentation for predicates
FuelLabs/fuels-ts pull request #1440
Opened 2023-11-18 10:45 UTC by KramPiotr

2023-11-18 10:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FuelLabs/fuels-ts?pullRequest=1440) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FuelLabs/fuels-ts?pullRequest=1440) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FuelLabs/fuels-ts?pullRequest=1440) it.</sub>

2023-11-18 12:02 UTC, arboleya requested changes
The predicate's binary and JSON ABI are obtained via `forc build`. 

If you want to expand the documentation and mention how to process these files before using them, by generating `types` via `fuels typegen`, you'll need to better elaborate the text, and properly link the related page at:
 - `/guide/abi-typegen/generating-types-from-abi.html#generating-types-for-predicates`

2023-12-10 16:12 UTC, danielbate commented
@KramPiotr are you still considering implementing this change?

2023-12-13 19:43 UTC, closed without merging

2023-12-13 19:43 UTC, arboleya commented
@KramPiotr Closing this since we didn't hear back from you.

Feel free to reopen if you still considering it.