fix: add keywords to npm description
FuelLabs/fuels-ts pull request #1453
Opened 2023-11-25 19:38 UTC by camsjams

As part of this issue https://github.com/FuelLabs/fuels-ts/issues/1397, I noticed that the [npm page](https://www.npmjs.com/package/fuels) doesn't show keywords:
![image](https://github.com/FuelLabs/fuels-ts/assets/833485/df4d14b8-d8df-4702-964f-6f886e8466bd)

Starting with a basic list for now.

2023-11-26 10:59 UTC, arboleya requested changes

2023-11-26 10:59 UTC, arboleya commented on packages/fuels/package.json
> +    "ethereum",
Good catch.

Does it make sense to at least start with the key names?

```suggestion
    "ethereum",
    "fuel",
    "sway",
    "forc",
```

2023-11-27 13:38 UTC, nedsalk approved these changes

2023-11-27 14:04 UTC, danielbate approved these changes

2023-11-27 15:30 UTC, merged