Wallet creation without provider
FuelLabs/fuels-ts pull request #1566
Opened 2023-12-19 17:21 UTC by petertonysmith94

### What have you done?

- Made the `Account.provider` member variable private.
- Added "getter" and "setter" methods, for the `provider` field.
- Throw an error when `Account.provider` is attempted to be "getted?"
- Removed redundant `provider` member variable on the `BaseWalletUnlocked` class

### What have I not done... (yet)

- `Account` Make the `provider` member variable protected
This will allow the variable to be accessed by is child classes (required for the `WalletLocked.unlock` and `WalletUnlocked.lock` methods).
- `BaseWalletUnlocked` make constructor `provider` argument optional
- `WalletUnlocked` make all methods with `provider` arguments optional
- `Wallet` make all methods with `provider` arguments optional
- `GenerateOptions` make argument for `provider` optional

### Assumed out of scope
- `MnemonicVault` 
- `PrivateKeyVault`

### Questions

1. Is this desired behaviour?
[code](https://github.com/FuelLabs/fuels-ts/blob/137ed8a5cf5534e91c1d5925dcc40f92b88affa4/packages/wallet/src/account.ts#L53)
```ts
const account = new Account(...) // or Wallet...
// Works
account.provider = new Provider(...)
```

I've replicated this behaviour to ensure this change isn't a breaking one. However, I believe we should depreciate this behaviour in favour of all using the `connect`method (this is a **breaking change**). 

2. Does this all look good, before I go steaming ahead with all the other areas that would need changes?

2024-01-09 18:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FuelLabs/fuels-ts?pullRequest=1566) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/FuelLabs/fuels-ts?pullRequest=1566) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: danielbate<br/>:white_check_mark: petertonysmith94<br/>:x: Torres-ssf<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FuelLabs/fuels-ts?pullRequest=1566) it.</sub>

2024-01-09 18:20 UTC, arboleya commented
Following #1444 milestone, this PR should target the `rc/salamander` branch / [PR](https://github.com/FuelLabs/fuels-ts/pull/1495).

2024-01-10 11:35 UTC, danielbate commented
@Torres-ssf it says you haven't signed the [CLA](https://github.com/FuelLabs/fuels-ts/pull/1566#issuecomment-1883547196) 🤯

2024-01-12 10:30 UTC, petertonysmith94 commented
Thank you @arboleya

2024-01-12 10:33 UTC, petertonysmith94 commented on .github/workflows/test.yaml
> +          github-token: ${{ secrets.GITHUB_TOKEN }}
Removing this now

2024-01-12 15:58 UTC, arboleya reviewed
This doesn't seem like a breaking change—_is it_?

The PR title incudes a `!`.

2024-01-12 15:58 UTC, arboleya commented on .changeset/witty-beds-vanish.md
> +---
Changeset should not be empty.

2024-01-12 20:54 UTC, petertonysmith94 commented
> This doesn't seem like a breaking change—_is it_?

No it doens't - removed the `!`

2024-01-17 12:04 UTC, Torres-ssf approved these changes
LGTM 🚀

2024-01-17 12:18 UTC, Torres-ssf requested changes
@petertonysmith94, thank you for your valuable contribution to this project 🙏.

I've reviewed the changes and I think they're great. 

However, I'd like to suggest an enhancement for our documentation. Specifically, in the Wallet section, it would be beneficial to clarify that the provider is optional when creating Wallet/Account instances.

2024-01-18 13:28 UTC, petertonysmith94 commented
> @petertonysmith94, thank you for your valuable contribution to this project 🙏.
> 
> I've reviewed the changes and I think they're great.
> 
> However, I'd like to suggest an enhancement for our documentation. Specifically, in the Wallet section, it would be beneficial to clarify that the provider is optional when creating Wallet/Account instances.

You're most welcome - I have added a small point on Wallet creation with an example.
Please let me know if there is anything else 😃

2024-01-18 13:33 UTC, Torres-ssf approved these changes

2024-01-18 13:56 UTC, danielbate approved these changes
:shipit:

2024-01-18 13:57 UTC, merged

2024-01-18 14:02 UTC, arboleya commented on apps/docs/src/guide/wallets/access.md
> +<<< @/../../../packages/fuel-gauge/src/doc-examples.test.ts#wallet-optional-provider{ts:line-numbers}
@FuelLabs/sdk-ts Just a reminder that code snippets should ideally come from the `apps/docs-snippets.`