fix: don't compare bn with integer
FuelLabs/fuels-ts pull request #1704
Opened 2024-02-02 13:18 UTC by nedsalk

This is a quick fix based on [this comment](https://github.com/FuelLabs/fuels-ts/pull/1603#issuecomment-1881210134).

2024-02-02 22:05 UTC, arboleya requested changes

2024-02-02 22:05 UTC, arboleya commented on .changeset/grumpy-countries-perform.md
> +"@fuel-ts/providers": minor
```suggestion
"@fuel-ts/providers": patch
```

2024-02-02 22:26 UTC, nedsalk commented on .changeset/grumpy-countries-perform.md
> +"@fuel-ts/providers": minor
https://edwardvilga.com/wp-content/uploads/2020/11/facepalm-head-768x432.jpg

2024-02-05 10:07 UTC, danielbate commented on packages/providers/src/coin-quantity.ts
> +    amount: bnAmount.isNeg() || bnAmount.isZero() ? bn(1) : bnAmount,
```suggestion
    amount: bnAmount.lt(1) ? bn(1) : bnAmount,
```

I can appreciate that based off [this comment](https://github.com/FuelLabs/fuels-ts/pull/1603#issuecomment-1881210134), `BN` ignores decimals so we can just check for negative / zero, however this is not obvious from the code. Wondering if using the built in `lt` function would be more succinct? Giving us both a `bn` comparison and the previous less than 1 use case.

2024-02-05 10:47 UTC, danielbate approved these changes

2024-02-05 10:49 UTC, arboleya approved these changes

2024-02-05 11:02 UTC, merged