Ps/feat/predicate factory generics
FuelLabs/fuels-ts pull request #1867
Opened 2024-03-12 16:29 UTC by petertonysmith94

Closes #1850 

- Added generic data input for the predicate factory.

2024-03-12 16:50 UTC, arboleya reviewed
@Dhaiwat10 Could you elaborate on your idea of inferring this type automatically from the ABI, if that still makes sense?

2024-03-13 02:38 UTC, Dhaiwat10 commented
@arboleya sure.

@petertonysmith94 I think the ideal DX for this `createInstance` method would be to not have the user pass in a generic, but _infer_ it from the ABI/typegen. We already know the 'shape' of the input that the predicate will accept when we generate types for it using the ABI. We should ideally use this information about the input's shape to pass that into the `Predicate` constructor. Does that make sense? Happy to elaborate over a huddle if unclear.

2024-03-13 07:08 UTC, Dhaiwat10 requested changes
Awesome work on the PR @petertonysmith94 👏🏻 

Could you please also export the type for the inputs from the typegen file in case someone wants to import it and use it like so:

```ts
import { PredicateInputType, PredicateFactory } from '@/types';

const predicateInputData: PredicateInputType = [20, 30];
const predicate = PredicateFactory.createInstance(provider, predicateInputData);
```

2024-03-13 15:40 UTC, arboleya approved these changes

2024-03-14 04:34 UTC, Dhaiwat10 approved these changes

2024-03-14 04:34 UTC, merged