docs: restructure documentation
FuelLabs/fuels-ts pull request #1906
Opened 2024-03-20 19:07 UTC by petertonysmith94

2024-03-20 19:49 UTC, petertonysmith94 commented on apps/docs/src/extras/utilities/address-conversion.md
> +# Address
Concatenated `guide/address/conversion.md` and `guide/address/index.md` together to get the `address-conversion`

2024-03-20 21:30 UTC, petertonysmith94 commented
Pipeline currently [failing](https://github.com/FuelLabs/fuels-ts/actions/runs/8365980048/job/22905114913?pr=1906#step:6:1174) on an assertion for the expected structure.

We could update the action [FuelLabs/github-actions](https://github.com/FuelLabs/github-actions/blob/master/docs-hub/vp-docs.js#L15C3-L15C46).

2024-03-21 17:42 UTC, danielbate commented
Nice work, I think my preference is option B as I'm concerned about compatibility with the docs hub.

2024-03-22 08:16 UTC, petertonysmith94 commented on apps/docs/src/guide/wallet-manager/index.md
Consolidated to `apps/docs/src/guide/wallets/wallet-manager.md`

2024-03-22 08:17 UTC, petertonysmith94 commented on apps/docs/src/guide/wallet-manager/locking-and-unlocking-wallet-manager.md
Consolidated to `apps/docs/src/guide/wallets/wallet-manager.md`

2024-03-22 08:18 UTC, petertonysmith94 commented on apps/docs/src/guide/wallets/wallet-manager.md
> +The `WalletManager` implements an automatic encryption mechanism, securely saving the wallet's held vaults. This not only preserves the state of your vaults but also ensures robust protection of the
This can be simplified IMO

2024-03-22 08:18 UTC, petertonysmith94 commented on apps/docs/src/guide/wallets/wallet-manager.md
>  # Getting Started with `WalletManager`
Wrong heading indent

2024-03-22 08:24 UTC, petertonysmith94 commented on apps/docs/src/guide/providers/querying-the-chain.md
> +<!-- TODO: Add docs for the two new parameters `commitBlockId` and `commitBlockHeight` -->
Consolidated various message docs into here

2024-03-22 08:25 UTC, petertonysmith94 commented on apps/docs/src/guide/predicates/predicate-with-more-complex-args.md
Moved to `apps/docs/src/guide/predicates/instantiating-a-predicate.md`

2024-03-22 08:25 UTC, petertonysmith94 commented on apps/docs/src/guide/predicates/index.md
> -
Moved to `apps/docs/src/guide/predicates/instantiating-a-predicate.md`

2024-03-22 08:28 UTC, petertonysmith94 commented on apps/demo-fuels/fuels.config.ts
> + * https://fuellabs.github.io/fuels-ts/tooling/cli/fuels/config-file
```suggestion
 * https://fuellabs.github.io/fuels-ts/guide/fuels/config-file
```

2024-03-22 08:30 UTC, petertonysmith94 commented on apps/docs/src/guide/cli/index.md
> -Use [`pnpm fuels init`](./commands#init) to create a [`fuel.config.ts`](./config-file) file.
Moved to `apps/docs/src/guide/fuels/index.md`

2024-03-22 08:31 UTC, petertonysmith94 commented on apps/docs/src/guide/contracts/index.md
> +# Deploying Contracts
```suggestion
# Contracts
```

2024-03-22 10:15 UTC, petertonysmith94 commented on apps/demo-fuels/fuels.config.ts
> + * https://fuellabs.github.io/fuels-ts/tooling/cli/fuels/config-file
https://github.com/FuelLabs/fuels-ts/commit/9a9dbbb9938414dc564426bc19383efde8550e00

2024-03-22 10:15 UTC, petertonysmith94 commented on apps/docs/src/guide/contracts/index.md
> +# Deploying Contracts
https://github.com/FuelLabs/fuels-ts/commit/4b47091c942ac4855b9bccc496f0fe220b3a5828

2024-03-22 10:25 UTC, petertonysmith94 commented on apps/docs/src/guide/wallets/wallet-manager.md
>  # Getting Started with `WalletManager`
https://github.com/FuelLabs/fuels-ts/commit/2d63f05a58db07b40771289abc9626fbb92f7ccc

2024-03-22 10:52 UTC, petertonysmith94 commented on apps/docs/src/guide/wallets/wallet-manager.md
> +The `WalletManager` implements an automatic encryption mechanism, securely saving the wallet's held vaults. This not only preserves the state of your vaults but also ensures robust protection of the
Will leave for https://github.com/FuelLabs/fuels-ts/issues/1919.

2024-03-22 14:34 UTC, danielbate approved these changes
Great work, good to get this in before we start to evolve the pages.

Approving as this does meet the specification for the restructure.

Couple thoughts:
- Are we keeping glossary, it's not in the new spec? We don't really maintain it and there and the docs hub has a glossary.
- Not sure how I feel about the contents tables, think I preferred the blurb about each section. And also it means we have to maintain 2 orders per section (links json and contents page)

2024-03-22 15:13 UTC, arboleya requested changes
Two things only:
 1. Initialize all main sections expanded
 3. Remove the Table of Contents page from all of them
    - Not only because it will be troublesome to maintain, but especially because it will not be present in the docs hub.

**Edit**: And yes, the glossary can go as well.

2024-03-23 08:06 UTC, petertonysmith94 commented
@arboleya and @danielbate - thanks for reviewing 🙏🏼 

Made the following changed, based on your comments:

- Removed table of contents
https://github.com/FuelLabs/fuels-ts/pull/1906/commits/a9eba896166a597199ef1b78d611f84dd6eeafcf
- Removed glossary
https://github.com/FuelLabs/fuels-ts/pull/1906/commits/653f7f04826cfbb03d39b0fe60fd18b5b26df9bf
- All main sections expanded
https://github.com/FuelLabs/fuels-ts/pull/1906/commits/b1588540ccf8117eccd5d0b88b24750494cdeb82

2024-03-25 09:41 UTC, danielbate approved these changes

2024-03-25 09:42 UTC, arboleya approved these changes

2024-03-25 10:58 UTC, arboleya approved these changes

2024-03-25 11:02 UTC, danielbate approved these changes

2024-03-25 11:08 UTC, merged