docs: reverted the doc menu categories
FuelLabs/fuels-ts pull request #2080
Opened 2024-04-17 08:51 UTC by petertonysmith94

Closes #2073 

---

- Reverted changes to the menu categories.

2024-04-17 10:28 UTC, arboleya commented on apps/docs/.vitepress/config.ts
> +        text: 'Guide',
To be as similar as possible to the docs hub, perhaps we should remove all sections, including `Introduction` and `Guide`, and have a flat list.

2024-04-17 10:57 UTC, arboleya commented on apps/docs/.vitepress/config.ts
> +        text: 'Guide',
Could all items look like the `Getting Started` and `Creating a Fuel dApp` items?

2024-04-17 15:07 UTC, arboleya submitted a review, later dismissed

2024-04-17 15:51 UTC, arboleya commented on apps/docs/.vitepress/config.ts
> +        text: 'Guide',
Unrelated to this PR, just cross-referencing these here:
 - https://github.com/FuelLabs/fuels-ts/issues/2086
 - https://github.com/FuelLabs/fuels-ts/issues/2087

2024-04-17 16:06 UTC, maschad requested changes

2024-04-17 20:25 UTC, maschad approved these changes
lgtm!

2024-04-17 21:03 UTC, arboleya approved these changes

2024-04-18 08:50 UTC, danielbate approved these changes

2024-04-18 09:06 UTC, merged