fix: encoding version type
FuelLabs/fuels-ts pull request #2126
Opened 2024-04-22 09:17 UTC by petertonysmith94

Closes #2124 

---

- Changed the `version` field on the `JsonAbi` to a string.
- Added validation on the encoding field.

2024-04-22 11:37 UTC, nedsalk commented on packages/abi-coder/src/utils/json-abi.ts
> +};
```suggestion
export const getEncodingVersion = (encoding?: string): EncodingVersion => {
  switch (encoding) {
    case undefined:
    case ENCODING_V0:
        return ENCODING_V0;

    case ENCODING_V1:
      return ENCODING_V1;

    default:
      throw new FuelError(
        ErrorCode.UNSUPPORTED_ENCODING_VERSION,
        `Encoding version '${encoding}' is unsupported.`
      );
  }
};
```
And you can remove the DEFAULT_ENCODING_VERSION constant with this.

2024-04-22 11:47 UTC, nedsalk commented on packages/abi-coder/src/types/JsonAbi.ts
> +  readonly encoding?: string;
Can you explain why we'd go from `EncodingVersion` to `string` when this field is optional to begin with so the user doesn't have to type it at all?

2024-04-22 14:44 UTC, maschad requested changes
Nice, but also need to address the comments that you made as well.

2024-04-22 14:44 UTC, maschad commented on packages/abi-coder/src/utils/constants.ts
> +export const DEFAULT_ENCODING_VERSION = ENCODING_V0;
Is the default always going to be `v0` ? If so then I don't think we need this constant and then @nedsalk 's [comment applies](https://github.com/FuelLabs/fuels-ts/pull/2126/files#r1574608969)

2024-04-23 01:41 UTC, maschad approved these changes
Great work!

2024-04-23 08:06 UTC, nedsalk approved these changes

2024-04-23 09:04 UTC, danielbate approved these changes
Good find 🦊 

This PR introduces some duplication for encoding version retrieval, however approving as this resolves the bug and I think that can be cleaned up #2109

2024-04-23 11:48 UTC, merged