docs: split up 'creating a fuel dapp' guide into multiple pages
FuelLabs/fuels-ts pull request #2134
Opened 2024-04-22 17:51 UTC by Dhaiwat10

Closes #2087

2024-04-23 01:49 UTC, maschad requested changes
Great work! Looks like CI docs are complaining about the new folder structure though

2024-04-23 01:49 UTC, maschad commented on apps/docs/src/guide/creating-a-fuel-dapp/adding-decrement-functionality.md
> +To add decrement functionality to our counter, we will have to do two things: 1. Add a `decrement_counter` function to our Sway contract, and 2. Modify the `./src/pages/index.tsx` file to add a butto
plus forgive my grammar nits but _To add decrement_ is a bit ironic 😄

```suggestion
In order to introduce decrement functionality to our counter, we will have to do two things: 1. Introduce a `decrement_counter` function to our Sway contract, and 2. Modify the `./src/pages/index.tsx` file to introduce a button that calls this function.
```

2024-04-23 01:49 UTC, maschad commented on apps/docs/src/guide/creating-a-fuel-dapp/adding-decrement-functionality.md
> +Second, we will add a new button to the UI that will call the `onDecrementPressed` function when clicked:
```suggestion
Secondly, we will add a new button to the UI that will call the `onDecrementPressed` function when clicked:
```

2024-04-23 01:49 UTC, maschad commented on apps/docs/src/guide/creating-a-fuel-dapp/adding-decrement-functionality.md
> +To add a `decrement_counter` function to our Sway contract, we will modify the `./sway-programs/contract/src/main.sw` file.
See https://github.com/FuelLabs/fuels-ts/pull/2134#discussion_r1575541584

2024-04-25 09:17 UTC, Dhaiwat10 commented
Closing as not planned after #2135

2024-04-25 09:17 UTC, closed without merging

2024-04-25 11:21 UTC, arboleya commented
I still think it makes sense to split this, but that will require a slight change in the menu order.

We can revisit this as we go.