chore: dependencies version consistency
FuelLabs/fuels-ts pull request #2235
Opened 2024-05-05 15:41 UTC by richardgreg

Fixes #2028

2024-05-06 11:05 UTC, danielbate requested changes

2024-05-06 11:05 UTC, danielbate commented on .github/workflows/pr-lint.yaml
> +        run: pnpm add --save-dev syncpack
Better to have this as a development dependency on the monorepo, so we can version it properly. And we have the config file committed anyways.

2024-05-15 20:05 UTC, maschad requested changes
Hi @richardgreg I think this is a great start. To finish up:

- you may want to define a syncpack config to avoid mismatches such as `workspace:*`
- Apparently there is a [Github action](https://github.com/marketplace/actions/syncpack-synchronise-monorepo-dependency-versions) which might save you some trouble

After that you can[ fix the mismatches ](https://jamiemason.github.io/syncpack/command/fix-mismatches/) then this should be ready for review

2024-06-06 17:12 UTC, maschad commented
Thanks for this work @richardgreg

I must apologize for an oversight on my part as it seems you would need [elevated permissions](https://github.com/JamieMason/syncpack-github-action/tree/main?tab=readme-ov-file#-installation) to be able to run this workflow accurately, which is why you are getting this [error](https://github.com/FuelLabs/fuels-ts/actions/runs/9308025797/job/25620535193?pr=2235#step:4:329)

I will take over the PR from here, merging your changes into one of my branches. Thanks for all of your work!

2024-08-02 19:54 UTC, maschad commented
Hi @richardgreg feel free to look through our [good first issues](https://github.com/FuelLabs/fuels-ts/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and see if there's anything that piques your interest.

2024-08-05 13:55 UTC, closed without merging