ci(changesets): versioning packages - `v0.84.1` @ `master`
FuelLabs/fuels-ts pull request #2236
Opened 2024-05-05 23:05 UTC by fuel-service-user

This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and the packages will be published to npm automatically. If you're not ready to do a release yet, that's fine, whenever you add more changesets to master, this PR will be updated.

# Releases
## @fuel-ts/abi-coder@0.84.1

### Patch Changes

-   Updated dependencies [f7eacb4]
    -   @fuel-ts/errors@0.84.1
    -   @fuel-ts/crypto@0.84.1
    -   @fuel-ts/math@0.84.1
    -   @fuel-ts/utils@0.84.1
    -   @fuel-ts/hasher@0.84.1
    -   @fuel-ts/interfaces@0.84.1

## @fuel-ts/abi-typegen@0.84.1

### Patch Changes

-   Updated dependencies [f7eacb4]
    -   @fuel-ts/errors@0.84.1
    -   @fuel-ts/utils@0.84.1
    -   @fuel-ts/interfaces@0.84.1
    -   @fuel-ts/versions@0.84.1

## @fuel-ts/account@0.84.1

### Patch Changes

-   f7eacb4: chore: warn on fuel client version incompatibility
-   Updated dependencies [f7eacb4]
    -   @fuel-ts/errors@0.84.1
    -   @fuel-ts/abi-coder@0.84.1
    -   @fuel-ts/address@0.84.1
    -   @fuel-ts/crypto@0.84.1
    -   @fuel-ts/math@0.84.1
    -   @fuel-ts/transactions@0.84.1
    -   @fuel-ts/utils@0.84.1
    -   @fuel-ts/hasher@0.84.1
    -   @fuel-ts/merkle@0.84.1
    -   @fuel-ts/interfaces@0.84.1
    -   @fuel-ts/versions@0.84.1

## @fuel-ts/address@0.84.1

### Patch Changes

-   Updated dependencies [f7eacb4]
    -   @fuel-ts/errors@0.84.1
    -   @fuel-ts/crypto@0.84.1
    -   @fuel-ts/utils@0.84.1
    -   @fuel-ts/interfaces@0.84.1

## @fuel-ts/contract@0.84.1

### Patch Changes

-   Updated dependencies [f7eacb4]
    -   @fuel-ts/account@0.84.1
    -   @fuel-ts/errors@0.84.1
    -   @fuel-ts/program@0.84.1
    -   @fuel-ts/abi-coder@0.84.1
    -   @fuel-ts/crypto@0.84.1
    -   @fuel-ts/transactions@0.84.1
    -   @fuel-ts/utils@0.84.1
    -   @fuel-ts/hasher@0.84.1
    -   @fuel-ts/merkle@0.84.1
    -   @fuel-ts/interfaces@0.84.1

## @fuel-ts/crypto@0.84.1

### Patch Changes

-   Updated dependencies [f7eacb4]
    -   @fuel-ts/errors@0.84.1
    -   @fuel-ts/utils@0.84.1

## @fuel-ts/errors@0.84.1

### Patch Changes

-   f7eacb4: chore: warn on fuel client version incompatibility
    -   @fuel-ts/versions@0.84.1

## fuels@0.84.1

### Patch Changes

-   Updated dependencies [f7eacb4]
    -   @fuel-ts/account@0.84.1
    -   @fuel-ts/errors@0.84.1
    -   @fuel-ts/contract@0.84.1
    -   @fuel-ts/program@0.84.1
    -   @fuel-ts/script@0.84.1
    -   @fuel-ts/abi-coder@0.84.1
    -   @fuel-ts/abi-typegen@0.84.1
    -   @fuel-ts/address@0.84.1
    -   @fuel-ts/crypto@0.84.1
    -   @fuel-ts/math@0.84.1
    -   @fuel-ts/transactions@0.84.1
    -   @fuel-ts/utils@0.84.1
    -   @fuel-ts/hasher@0.84.1
    -   @fuel-ts/merkle@0.84.1
    -   @fuel-ts/forc@0.84.1
    -   @fuel-ts/fuel-core@0.84.1
    -   @fuel-ts/interfaces@0.84.1
    -   @fuel-ts/versions@0.84.1

## @fuel-ts/hasher@0.84.1

### Patch Changes

-   @fuel-ts/crypto@0.84.1
-   @fuel-ts/utils@0.84.1
-   @fuel-ts/interfaces@0.84.1

## @fuel-ts/math@0.84.1

### Patch Changes

-   Updated dependencies [f7eacb4]
    -   @fuel-ts/errors@0.84.1

## @fuel-ts/merkle@0.84.1

### Patch Changes

-   @fuel-ts/math@0.84.1
-   @fuel-ts/hasher@0.84.1

## @fuel-ts/program@0.84.1

### Patch Changes

-   Updated dependencies [f7eacb4]
    -   @fuel-ts/account@0.84.1
    -   @fuel-ts/errors@0.84.1
    -   @fuel-ts/abi-coder@0.84.1
    -   @fuel-ts/address@0.84.1
    -   @fuel-ts/math@0.84.1
    -   @fuel-ts/transactions@0.84.1
    -   @fuel-ts/utils@0.84.1
    -   @fuel-ts/interfaces@0.84.1

## @fuel-ts/script@0.84.1

### Patch Changes

-   Updated dependencies [f7eacb4]
    -   @fuel-ts/account@0.84.1
    -   @fuel-ts/errors@0.84.1
    -   @fuel-ts/program@0.84.1
    -   @fuel-ts/abi-coder@0.84.1
    -   @fuel-ts/address@0.84.1
    -   @fuel-ts/math@0.84.1
    -   @fuel-ts/transactions@0.84.1
    -   @fuel-ts/utils@0.84.1
    -   @fuel-ts/interfaces@0.84.1

## @fuel-ts/transactions@0.84.1

### Patch Changes

-   Updated dependencies [f7eacb4]
    -   @fuel-ts/errors@0.84.1
    -   @fuel-ts/abi-coder@0.84.1
    -   @fuel-ts/address@0.84.1
    -   @fuel-ts/math@0.84.1
    -   @fuel-ts/utils@0.84.1
    -   @fuel-ts/hasher@0.84.1
    -   @fuel-ts/interfaces@0.84.1

## @fuel-ts/utils@0.84.1

### Patch Changes

-   Updated dependencies [f7eacb4]
    -   @fuel-ts/errors@0.84.1
    -   @fuel-ts/interfaces@0.84.1

## create-fuels@0.84.1

## @fuel-ts/forc@0.84.1

## @fuel-ts/fuel-core@0.84.1

## @fuel-ts/interfaces@0.84.1

## @fuel-ts/versions@0.84.1

2024-05-06 09:37 UTC, arboleya requested changes
> [!WARNING]
> Do not release before:
> - https://github.com/FuelLabs/changesets-action/pull/9

2024-05-10 12:58 UTC, arboleya approved these changes

2024-05-10 13:26 UTC, nedsalk approved these changes

2024-05-10 13:29 UTC, Torres-ssf approved these changes

2024-05-10 13:39 UTC, merged