chore: treat minor changes as breaking
FuelLabs/fuels-ts pull request #2275
Opened 2024-05-09 07:06 UTC by nedsalk

closes #2244

2024-05-09 09:53 UTC, arboleya submitted a review, later dismissed

2024-05-09 09:53 UTC, arboleya commented on .github/workflows/pr-lint.yaml
> +              echo "Changeset has minor changes. Please mark the PR as breaking by adding an exclamation mark to its title (e.g. fix!: xxx)."
Nit.

```suggestion
              echo "Changeset has `minor` changes. Please mark the PR as breaking by adding an exclamation mark to its title (e.g. fix!: xxx) or use a `patch` instead."
```

2024-05-09 10:01 UTC, arboleya submitted a review, later dismissed

2024-05-09 13:11 UTC, Torres-ssf submitted a review, later dismissed

2024-05-09 16:15 UTC, maschad requested changes
Looks good, just want to include a TODO so it doesn't get lost in the ether... 😉

2024-05-09 16:15 UTC, maschad commented on .github/workflows/pr-lint.yaml
```suggestion
#TODO: Remove once v1.0.0 is released.
```

2024-05-10 07:24 UTC, danielbate submitted a review, later dismissed

2024-05-10 09:58 UTC, arboleya approved these changes

2024-05-10 10:11 UTC, merged