chore: added linting for pnpm-lock file quotes
FuelLabs/fuels-ts pull request #2301
Opened 2024-05-14 14:05 UTC by petertonysmith94

Adds linting to our `pnpm-lock.yaml` to allow for consistent quotes which enables reviewing of the dependency changes in the lock file.

Examples of these changes [here](https://github.com/FuelLabs/fuels-ts/pull/2130/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bb) and [here](https://github.com/FuelLabs/fuels-ts/pull/2218/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bb).

2024-05-14 16:51 UTC, maschad reviewed
Is this supposed to enable reviewing the lockfile on github? because that's still not possible.

2024-05-14 19:08 UTC, maschad requested changes
Looks like there is still a [linting issue](https://github.com/FuelLabs/fuels-ts/actions/runs/9083627872/job/24962715009?pr=2301#step:8:22)

2024-05-14 21:54 UTC, maschad approved these changes
Nice

2024-05-15 06:41 UTC, danielbate approved these changes

2024-05-15 07:09 UTC, merged