fix: update testnet URL
FuelLabs/fuels-ts pull request #2430
Opened 2024-05-31 15:59 UTC by petertonysmith94

Closes #2427

2024-05-31 16:21 UTC, maschad requested changes
I think there are a few missing files:

- https://github.com/FuelLabs/fuels-ts/blob/master/CONTRIBUTING.md?plain=1#L141
- https://github.com/FuelLabs/fuels-ts/blob/master/.github/workflows/test.yaml#L80
- https://github.com/FuelLabs/fuels-ts/blob/master/apps/docs-snippets/src/guide/wallets/instantiating-wallets.test.ts#L103
- https://github.com/FuelLabs/fuels-ts/blob/master/packages/fuel-gauge/src/e2e-script.test.ts#L50

2024-05-31 16:51 UTC, maschad approved these changes

2024-05-31 20:44 UTC, Dhaiwat10 submitted a review, later dismissed

2024-06-04 14:16 UTC, arboleya reviewed
E2E's are failing.

2024-06-04 17:06 UTC, maschad approved these changes

2024-06-05 17:12 UTC, arboleya approved these changes

2024-06-05 17:22 UTC, Dhaiwat10 approved these changes

2024-06-05 17:22 UTC, merged