Add readmes for each package
FuelLabs/fuels-ts pull request #249
Opened 2022-05-07 00:01 UTC by camsjams

Fixes #153

I've taken a first pass on each description, we can opine on the `description` of each package and the overall contents of the READMEs.

I can make changes easily because they are generated using a base markdown file that I've created locally, which I've copied below.

<details><summary>See base markdown template</summary>

```
# `_PACKAGE_NAME_`

**_PACKAGE_NAME_** is a sub-module for interacting with **Fuel**.

_PACKAGE_DESC_

# Table of contents

- [Documentation](#documentation)
- [Usage](#usage)
  - [Installation](#installation)
  - [Full SDK Installation](#full-sdk-installation)
- [Contributing](#contributing)
- [Changelog](#changelog)
- [License](#license)

## Documentation

See [Fuel TypeScript SDK Documentation](https://fuellabs.github.io/fuels-ts/)

## Usage

### Installation

```sh
yarn add _PACKAGE_NAME_
# or
npm add _PACKAGE_NAME_
```

### Full SDK Installation

Alternatively, we recommend you install the [complete SDK](https://github.com/FuelLabs/fuels-ts) using the umbrella package:

```sh
yarn add fuels
# or
npm add fuels
```

## Contributing

In order to contribute to `_PACKAGE_NAME_`, please see the main [fuels-ts](https://github.com/FuelLabs/fuels-ts) monorepo.

## Changelog

The `_PACKAGE_NAME_` changelog can be found at [CHANGELOG](./CHANGELOG.md).

## License

The primary license for `_PACKAGE_NAME_` is `Apache 2.0`, see [LICENSE](./LICENSE).```
</details>

2022-05-09 18:07 UTC, luizstacio requested changes

2022-05-09 18:07 UTC, luizstacio commented on packages/abi-coder/README.md
> +Alternatively, we recommend you install the [complete SDK](https://github.com/FuelLabs/fuels-ts) using the umbrella package:
❤️

2022-05-09 18:44 UTC, camsjams commented on packages/abi-coder/README.md
> +See [Fuel TypeScript SDK Documentation](https://fuellabs.github.io/fuels-ts/)
Yes this is possible - good point!

2022-05-11 05:42 UTC, camsjams commented on packages/abi-coder/README.md
> +See [Fuel TypeScript SDK Documentation](https://fuellabs.github.io/fuels-ts/)
Updated :+1:

2022-05-11 05:43 UTC, camsjams commented on typedoc.json
> +    "packages/wordlists"
These are all packages aside from `fuels` and `sample-contract`

2022-05-11 18:52 UTC, luizstacio approved these changes
LGTM! Nice work

2022-05-11 18:56 UTC, merged