chore: add permissions for pr labeller
FuelLabs/fuels-ts pull request #2577
Opened 2024-06-21 20:14 UTC by petertonysmith94

Fixing mistake from #2576

2024-06-21 20:28 UTC, arboleya submitted a review, later dismissed

2024-06-21 20:41 UTC, maschad requested changes
Two things: 

- Why hasn't the label been automagically added to this PR?
- Shouldn't we need to add:

```yaml
permissions:
  pull-requests: write 
```

according to the [usage docs](https://github.com/fuxingloh/multi-labeler#usage)

2024-06-21 21:57 UTC, arboleya commented
> Why hasn't the label been automagically added to this PR?

@maschad New workflows must first go to `master` before they can run, no?

2024-06-21 22:03 UTC, maschad commented
> > Why hasn't the label been automagically added to this PR?
> 
> @maschad New workflows must first go to `master` before they can run, no?

My tendency was to think so as well, but I did note when this job was [introduced](https://github.com/FuelLabs/fuels-ts/pull/2383) the automation was applied. It may be because the current commit still has the conditional though. 

<img width="593" alt="Screenshot 2024-06-21 at 5 02 27 PM" src="https://github.com/FuelLabs/fuels-ts/assets/9755286/874c0938-6527-4b65-af37-3545cafde8bd">

2024-06-21 22:03 UTC, maschad approved these changes

2024-06-22 09:46 UTC, arboleya approved these changes

2024-06-24 07:41 UTC, danielbate approved these changes

2024-06-24 14:10 UTC, merged