chore: remove breaking changes PR workflow
FuelLabs/fuels-ts pull request #2631
Opened 2024-06-26 14:48 UTC by Torres-ssf

- Close: https://github.com/FuelLabs/fuels-ts/issues/2630

2024-06-26 14:50 UTC, danielbate submitted a review, later dismissed

2024-06-26 15:52 UTC, maschad commented on .changeset/forty-mice-talk.md
> +chore: remove breaking changes PR workflow
```suggestion
ci: remove breaking changes PR workflow
```

2024-06-26 15:53 UTC, maschad requested changes
We can label this a `ci` change

2024-06-26 17:40 UTC, maschad approved these changes

2024-06-27 10:53 UTC, arboleya approved these changes

2024-06-27 10:55 UTC, danielbate approved these changes

2024-06-27 11:06 UTC, merged