ci: fix dependabot script not bumping packages in changeset
FuelLabs/fuels-ts pull request #2640
Opened 2024-06-28 08:31 UTC by nedsalk

- closes #2594

2024-06-28 17:17 UTC, maschad approved these changes
This is great work. My only suggestion would be given this has failed before in the past, it may be useful to have some logging added should this have issues going forward.

2024-06-28 17:17 UTC, maschad commented on scripts/changeset/dependabot-changeset.sh
> +changed_templates=$(echo "$changed_files" | grep -E "templates/.+/package.json")
Let's log these out as well.

```suggestion
changed_packages=$(echo "$changed_files" | grep -E "packages/.+/package.json" | xargs jq -r '.name')
changed_templates=$(echo "$changed_files" | grep -E "templates/.+/package.json")

echo "changed packages: $changed_packages"
echo "changed templates: $changed_templates"
```

2024-06-28 17:17 UTC, maschad commented on scripts/changeset/dependabot-changeset.sh
> +changed_files=$(git diff-tree --no-commit-id --name-only -r "$first_commit")
```suggestion
changed_files=$(git diff-tree --no-commit-id --name-only -r "$first_commit")
echo "changed files: $changed_files"
```

2024-06-28 17:17 UTC, maschad commented on scripts/changeset/dependabot-changeset.sh
> +first_commit=$(git log master..HEAD --oneline --reverse | xargs | awk '{print $1;}')
```suggestion
first_commit=$(git log master..HEAD --oneline --reverse | xargs | awk '{print $1;}')
echo "First commit: $first_commit"
```

2024-06-28 18:37 UTC, maschad submitted a review, later dismissed

2024-06-29 14:20 UTC, arboleya approved these changes

2024-06-29 14:23 UTC, arboleya requested changes

2024-06-29 14:23 UTC, arboleya commented on scripts/changeset/dependabot-changeset.sh
> +changed_packages=$(echo "$changed_files" | grep -E "packages/.+/package.json" | xargs jq -r '.name')
```suggestion
# Get the list of relevant package.json changes
changed_packages=$(echo "$changed_files" | grep -E "packages/.+/package.json" | xargs jq -r '.name')
```

2024-06-29 15:11 UTC, maschad approved these changes

2024-06-29 15:11 UTC, danielbate approved these changes

2024-06-29 17:06 UTC, arboleya approved these changes

2024-06-29 17:06 UTC, merged