chore: added code of conduct
FuelLabs/fuels-ts pull request #2737
Opened 2024-07-08 15:22 UTC by petertonysmith94

- Closes #2129 

# Summary

- Using [`fuel-ui`](https://github.com/FuelLabs/fuel-ui/blob/master/CODE_OF_CONDUCT.md) for reference, added a code of conduct, using the latest (v2.1) Contributor Covenant Code of Conduct.

# Checklist

- [ ] I **_added_** — `tests` to prove my changes
- [ ] I **_updated_** — all the necessary `docs`
- [X] I **_reviewed_** — the entire PR myself, using the GitHub UI
- [ ] I **_described_** — all breaking changes and the Migration Guide

2024-07-08 17:02 UTC, maschad requested changes
This is an [empty file,](https://github.com/FuelLabs/fuels-ts/pull/2737/files#diff-ffdbe3a1e7ee93cacfc080b6c635ccf3a8f6b0f00f2fb884f78c6b5f9dac8fd2) is this intentional?

2024-07-09 17:49 UTC, Torres-ssf requested changes
👏

2024-07-09 17:49 UTC, Torres-ssf commented on CODE_OF_CONDUCT.md
> +[our Discord](https://discord.com/invite/xfpK4Pe).
```suggestion
reported to the community leaders responsible for enforcement on
[our Discord](https://discord.com/invite/xfpK4Pe).
```

2024-07-09 17:49 UTC, Torres-ssf commented on CODE_OF_CONDUCT.md
> +response to any behavior that they deem inappropriate, threatening, offensive,
```suggestion
response to any behavior deemed inappropriate, threatening, offensive,
```

2024-07-09 17:49 UTC, Torres-ssf commented on CODE_OF_CONDUCT.md
> +We as members, contributors, and leaders pledge to make participation in our
```suggestion
We, as members, contributors, and leaders, pledge to make participation in our
```

2024-07-10 10:08 UTC, danielbate approved these changes

2024-07-10 10:22 UTC, Torres-ssf approved these changes

2024-07-10 16:47 UTC, maschad approved these changes
🤝

2024-07-11 06:26 UTC, merged