Update TypeChain to v8
FuelLabs/fuels-ts pull request #283
Opened 2022-05-18 18:45 UTC by camsjams

Fixes #279 

Unblocks https://github.com/FuelLabs/swayswap/issues/104

2022-05-18 18:53 UTC, luizstacio requested changes

2022-05-18 18:53 UTC, luizstacio commented on package.json
> +    "test:glob": "jest $FILE_PATH --verbose",
Passing just `pnpm test src/example-contract.test.ts` should work also if you need --verbose it also works fine.

```
"test:glob": "jest--verbose",
```
 pnpm test:glob src/example-contract.test.ts

2022-05-18 19:11 UTC, luizstacio approved these changes
⚡️⚡️

2022-05-19 00:03 UTC, QuinnLee approved these changes

2022-05-19 17:46 UTC, AlicanC approved these changes

2022-05-19 17:46 UTC, AlicanC commented
Didn't have a chance to test but looking good 👍

2022-05-19 18:02 UTC, merged