feat: support basic auth
FuelLabs/fuels-ts pull request #3079
Opened 2024-09-02 15:06 UTC by nedsalk

- Closes #3069 

# Release notes

In this release, we:
- Added support for basic auth `https://my-username:my-password@mainnet.fuel.network/v1/graphql`

# Checklist

- [ ] All **changes** are **covered** by **tests** (or not applicable)
- [ ] All **changes** are **documented** (or not applicable)
- [ ] I **reviewed** the **entire PR** myself (preferably, on GH UI)
- [ ] I **described** all **Breaking Changes** (or there's none)

2024-09-02 15:38 UTC, petertonysmith94 submitted a review, later dismissed

2024-09-02 16:35 UTC, arboleya requested changes
Left a couple of suggestions to simplify the flow.

Pseudo-code, pls double-check.

2024-09-02 16:35 UTC, arboleya commented on packages/account/src/providers/provider.ts
> +  private static handleBasicAuth(url: string): [string, ProviderOptions['requestMiddleware']] {
Rename to fit next suggestions.

```suggestion
  private static extractBasicAuth(url: string): [string, ProviderOptions['requestMiddleware']] {
```

2024-09-02 16:35 UTC, arboleya commented on packages/account/src/providers/provider.ts
> +    ];
Removing side-effects, keeping it simple.

```suggestion
    return { url, auth };
```

2024-09-02 16:35 UTC, arboleya commented on packages/account/src/providers/provider.ts
> +    const [urlToUse, addBasicAuth] = this.handleBasicAuth(url);
According to the previous suggestions:

```suggestion
    const { url: urlToUse, auth } = this.extractBasicAuth(url);
```

2024-09-02 16:35 UTC, arboleya commented on packages/account/src/providers/provider.ts
> +      },
Injecting auth conditionally within the flow.

```suggestion
      requestMiddleware: async (request: <TypeHere>) => {
        if (auth) {
          request.headers ??= {};
          request.headers.Authorization = auth;
        }

        return options.requestMiddleware?.(request) ?? request;
      },
```

2024-09-03 07:00 UTC, petertonysmith94 approved these changes

2024-09-03 08:06 UTC, danielbate approved these changes

2024-09-03 10:40 UTC, Torres-ssf approved these changes

2024-09-03 11:11 UTC, arboleya approved these changes

2024-09-03 11:11 UTC, merged