Update array and tuple formats in  typechain  target
FuelLabs/fuels-ts pull request #315
Opened 2022-06-06 15:11 UTC by QuinnLee

WIP

2022-06-27 15:03 UTC, QuinnLee commented on README.md
> +| enum      | Partial<Object>                    |
Going to update with https://github.com/FuelLabs/fuels-ts/issues/359

2022-06-28 03:09 UTC, luizstacio requested changes

2022-06-28 03:09 UTC, luizstacio commented on packages/typechain-target-fuels/src/parser/abiParser.ts
> +  registerStruct: (datum: StructType | EnumType | TupleType) => void,
I see that this combination repeats a lot maybe create a single type for it;
`type DatumType = StructType | EnumType | TupleType`?

2022-06-28 13:59 UTC, QuinnLee commented on packages/typechain-target-fuels/src/codegen/types.ts
> +      if (svmType.structName && options.useStructs) {
it does, but we may need to rename it.  It's a flag to tell the codegen to create the `type foo =` definition for the type. It used to be just for structs but now is for other types

2022-06-28 14:16 UTC, QuinnLee commented on packages/typechain-target-fuels/src/parser/abiParser.ts
> +      datum.type === 'struct' &&
done! I had to do some casting but it's effectively equivalent

2022-06-28 17:49 UTC, merged