feat: add predicate support
FuelLabs/fuels-ts pull request #331
Opened 2022-06-14 23:03 UTC by camsjams

Closes #304 

Will be enhanced once https://github.com/FuelLabs/sway/issues/1981 is completed

PR for Sway is ready for review: https://github.com/FuelLabs/sway/pull/1984

2022-06-15 17:41 UTC, QuinnLee commented on packages/predicate/package.json
> +  "version": "0.6.0",
```suggestion
  "version": "0.7.0",
```

2022-06-15 22:56 UTC, adlerjohn reviewed
As a general framework it looks fine. Will have to be replaced by the stdlib version once that's available as you noted.

2022-06-15 22:56 UTC, adlerjohn commented on packages/predicate/src/test-predicate-basic/Forc.lock
> +source = 'git+https://github.com/fuellabs/sway?tag=v0.14.5#60c626cf486d5c53c44d84db1ec81cb90174cad3'
Not a fan of how this uses a hard-coded and old version of `forc`. But this is a repo-wide issue I think?

2022-06-15 23:31 UTC, adlerjohn commented on packages/predicate/src/test-predicate-basic/Forc.lock
> +source = 'git+https://github.com/fuellabs/sway?tag=v0.14.5#60c626cf486d5c53c44d84db1ec81cb90174cad3'
It is what it is

2022-06-15 23:31 UTC, adlerjohn reviewed
CI failing

2022-06-16 02:19 UTC, adlerjohn commented
In that case I would hold off on merging this PR until it's unblocked by stdlib inclusion of getting predicate data correctly. Don't want to have CI failing in `master`.

2022-06-20 15:41 UTC, QuinnLee commented
do the changes https://github.com/FuelLabs/fuels-ts/pull/344 conflict

2022-06-20 22:49 UTC, luizstacio requested changes
Are the contracts present on the predicate only for tests? If yes, I think we should avoid committing the binaries and lock files, just the minimal files requested, as it should be built again on `build-time`

2022-06-21 00:03 UTC, AlicanC requested changes
Requested changes are here: https://github.com/FuelLabs/fuels-ts/pull/349

2022-06-21 04:42 UTC, luizstacio approved these changes

2022-06-21 18:49 UTC, AlicanC approved these changes

2022-06-27 05:10 UTC, merged