chore(packages): added noImplicitOverride option to config
FuelLabs/fuels-ts pull request #3384
Opened 2024-11-12 11:56 UTC by YaTut1901

- Closes https://github.com/FuelLabs/fuels-ts/issues/3275

# Checklist

- [ ] All **changes** are **covered** by **tests** (or not applicable)
- [ ] All **changes** are **documented** (or not applicable)
- [ ] I **reviewed** the **entire PR** myself (preferably, on GH UI)
- [ ] I **described** all **Breaking Changes** (or there's none)

2024-11-14 03:44 UTC, petertonysmith94 commented on .changeset/strange-starfishes-raise.md
> +chore(packages): added noImplicitOverride option to config
```suggestion
chore: added noImplicitOverride option to config
```

2024-11-14 03:44 UTC, petertonysmith94 commented on packages/abi-coder/src/encoding/coders/EnumCoder.ts
> +  public coders: TCoders;
```suggestion
  override name: string;
  coders: TCoders;
```

Why change the access visibility here?

2024-11-14 03:44 UTC, petertonysmith94 commented on packages/abi-coder/src/encoding/coders/StructCoder.ts
> +  public coders: TCoders;
```suggestion
  override name: string;
  coders: TCoders;
```

2024-11-14 03:44 UTC, petertonysmith94 commented on packages/abi-coder/src/encoding/coders/OptionCoder.ts
> +  public override encode(value?: Option<unknown>): Uint8Array {
```suggestion
  override encode(value?: Option<unknown>): Uint8Array {
```

2024-11-14 03:44 UTC, petertonysmith94 commented on packages/abi-coder/src/encoding/coders/OptionCoder.ts
> +  public override decode(data: Uint8Array, offset: number): [DecodedValueOf<TCoders>, number] {
```suggestion
  override decode(data: Uint8Array, offset: number): [DecodedValueOf<TCoders>, number] {
```

2024-11-14 08:47 UTC, petertonysmith94 approved these changes

2024-11-14 10:26 UTC, danielbate requested changes

2024-11-14 10:26 UTC, danielbate commented on .changeset/strange-starfishes-raise.md
> +"@fuel-ts/script": patch
Please regenerate the changeset as this looks like it's missing packages.

2024-11-15 01:46 UTC, Torres-ssf requested changes

2024-11-15 01:46 UTC, Torres-ssf commented on .changeset/strange-starfishes-raise.md
> +chore: added noImplicitOverride option to config
@YaTut1901 It appears that we have 2 changeset files being added. We can safely remove `strange-starfishes-raise.md`. 

`large-points-arrive.md` seems to be already correct

2024-11-15 01:47 UTC, petertonysmith94 commented on .changeset/strange-starfishes-raise.md
@YaTut1901 please delete this changeset :)

2024-11-18 09:36 UTC, petertonysmith94 approved these changes

2024-11-18 14:12 UTC, Torres-ssf approved these changes

2024-11-18 14:28 UTC, maschad approved these changes
Thanks for the great work @YaTut1901 🚀

2024-11-18 14:31 UTC, merged