chore: add storage slot snippets to `docs-snippets2`
FuelLabs/fuels-ts pull request #3390
Opened 2024-11-12 19:19 UTC by Dhaiwat10

# Release notes

In this release, we:

- Did this and that 

# Summary

# Breaking Changes

# Checklist

- [ ] All **changes** are **covered** by **tests** (or not applicable)
- [ ] All **changes** are **documented** (or not applicable)
- [ ] I **reviewed** the **entire PR** myself (preferably, on GH UI)
- [ ] I **described** all **Breaking Changes** (or there's none)

2024-11-13 03:20 UTC, Dhaiwat10 commented on apps/docs-snippets2/src/contracts/deploying-contracts/storage-slots.ts
> +import { LOCAL_NETWORK_URL, WALLET_PVT_KEY } from '../../env';
For some reason, I had to leave this line inside of the `#region`, otherwise the generated test file would break. 👀

2024-11-14 03:19 UTC, Torres-ssf requested changes

2024-11-14 03:19 UTC, Torres-ssf commented on apps/docs-snippets2/src/contracts/deploying-contracts/storage-slots.ts
> +// #context import storageSlots from '../your-sway-project/out/debug/your-sway-project-storage_slots.json';
We do not need to migrate #context snippets tags anymore.

2024-11-14 03:22 UTC, closed without merging

2024-11-14 03:22 UTC, petertonysmith94 commented
I have cherry-picked the script commit into https://github.com/FuelLabs/fuels-ts/pull/3369. Going to close this PR after a discussion with Dhai.