chore: dependency pinning and audit
FuelLabs/fuels-ts pull request #3449
Opened 2024-12-05 21:27 UTC by danielbate

- Closes #3448 

# Summary

Adds `pnpm audit` in CI and pins dependency versions.

# Checklist

- [ ] All **changes** are **covered** by **tests** (or not applicable)
- [ ] All **changes** are **documented** (or not applicable)
- [ ] I **reviewed** the **entire PR** myself (preferably, on GH UI)
- [ ] I **described** all **Breaking Changes** (or there's none)

2024-12-05 22:41 UTC, maschad requested changes
Dependabot already alerts us of existing vulnerabilities in our dependencies, so I don't believe this CI check is necessary. 

Also I'm not sure if dependency pinning serves as a defence against upgrading to malicious software:

1. We already commit our lockfile, and so `pnpm` will install the same versions of the dependency. So if a vulnerability is discovered in an audit, we should actually upgrade to the patched version as opposed to keeping the dependency pinned at a particular version.

2. Even pinned versions can become compromised retroactively - an attacker could gain access to the package registry account and replace the package content while keeping the same version number  - we could explore using [provenance logs](https://docs.npmjs.com/generating-provenance-statements) for npm packages in such a case, but not my deps provide them unfortunately. That being said It still may be worthwhile to run `pnpm audit signatures` in the future.

2024-12-06 10:12 UTC, danielbate commented
@maschad neither of these changes were intended as full-proof solutions, but merely mitigation. Agreed deps can be retroactively compromised and we commit our lock file.

Pinning dependencies does mitigate risk of us upgrading to a compromised version, which in my experience is a more common risk. 

Good point on the `audit`, with pinning in place we would only be upgrading from dependabot, so it would be redundant.

2024-12-06 10:16 UTC, petertonysmith94 reviewed
Nice 🪨 🌟

2024-12-06 10:16 UTC, petertonysmith94 commented on .changeset/fluffy-cooks-worry.md
> +chore: dependency pinning and audit
```suggestion
chore: dependency pinning
```

2024-12-06 10:18 UTC, Dhaiwat10 submitted a review, later dismissed

2024-12-06 10:22 UTC, petertonysmith94 submitted a review, later dismissed

2024-12-06 14:44 UTC, Torres-ssf submitted a review, later dismissed

2024-12-06 17:09 UTC, maschad commented
> @maschad neither of these changes were intended as full-proof solutions, but merely mitigation. Agreed deps can be retroactively compromised and we commit our lock file.
> 
> Pinning dependencies does mitigate risk of us upgrading to a compromised version, which I believe is a more common risk.
> 
> Good point on the `audit`, with pinning in place we would only be upgrading from dependabot, so it would be redundant.


Thanks for the clarification @danielbate 

Upon further consideration, I believe we could strengthen our security approach by adding `pnpm audit` specifically to our release workflow. This would ensure we never release with any _known_ vulnerabilities. So I would welcome that change. Of course we can also simultaneously still benefit from the dependabot security alerts as well, perhaps we need to revisit the dependabot upgrade workflows to ensure that process is more streamlined.

While version pinning seems like it would increase security through strict control, it can actually work against us by making it harder to receive automatic security fixes, bug fixes, and improvements. Since we already commit our _lockfile_, we get the best of both worlds: reproducible builds through the _lockfile_, plus the ability to receive ranged upgrades with important fixes.

What are your thoughts on this approach?

2024-12-10 12:10 UTC, Dhaiwat10 commented
I agree with adding `pnpm audit` as a part of our CI. I believe the frontend team has this as well

2024-12-10 13:01 UTC, danielbate commented
Thankyou for the investigation @maschad, agreed with you and @Dhaiwat10 I'll implement audit here. Although that will introduce some upgrade problems which I'll need to fix, so I'll convert this to draft.

Re dep pinning, I did take a look at something @petertonysmith94 mentioned in sync yesterday, that although we do commit the lock file, it isn't included in our [published distribution](https://www.npmjs.com/package/fuels?activeTab=code) so only benefits us in development and not consumers installing `fuels`. So they would still be at risk of installing a compromised package installed by a range dependency?

2024-12-10 13:42 UTC, danielbate commented on .github/workflows/audit.yaml
> +name: "Audit"
We may want to hold this till after the release this week as there audit issues to resolve.

2024-12-10 14:00 UTC, danielbate commented on .changeset/fluffy-cooks-worry.md
> +chore: dependency pinning
```suggestion
chore: dependency pinning and auditing
```

2024-12-10 16:59 UTC, danielbate commented
I caught up with @maschad earlier and we agreed that implementing audit on release is a good idea to ensure we aren't shipping with compromised versions. We also agreed that committing the lock file doesn't protect consumers of `fuels`. So we are left with a file predicament that is do we:
- Pin versions in an attempt to protect consumers from malicious upgrades, but they also miss out on security updates, and we're still at risk of a pinned version being compromised
- Keep the range versions to protect consumers by ensuring they can receive security updates by having the latest version

This feels like a bit of play off and would appreciate another opinion @FuelLabs/sdk-ts.

A potential solution that @maschad did propose would be to pin the consumer versions (prod deps inside `fuels`) but allow ranges for our dev deps so we can still benefit from security upgrades internally.

2024-12-11 14:48 UTC, petertonysmith94 submitted a review, later dismissed

2024-12-12 12:38 UTC, Torres-ssf approved these changes

2024-12-12 13:10 UTC, Dhaiwat10 submitted a review, later dismissed

2024-12-12 13:58 UTC, arboleya approved these changes

2024-12-12 15:10 UTC, danielbate commented
Okay I'm taking the approvals as agreement. Will hold off till after this weeks release window and then will merge, as I'll resolve the audit issues over the holiday period.

2024-12-17 14:12 UTC, arboleya submitted a review, later dismissed

2024-12-17 16:54 UTC, petertonysmith94 submitted a review, later dismissed

2025-01-02 09:14 UTC, petertonysmith94 commented on .github/workflows/audit.yaml
> +name: "Audit"
Have we resolved the audit issues?

2025-01-02 10:37 UTC, arboleya approved these changes

2025-01-02 11:39 UTC, petertonysmith94 commented on .github/workflows/audit.yaml
> +name: "Audit"
I have skipped the audit and added this following issue:
- https://github.com/FuelLabs/fuels-ts/issues/3524

2025-01-02 12:05 UTC, petertonysmith94 approved these changes

2025-01-02 12:15 UTC, Torres-ssf approved these changes

2025-01-02 12:43 UTC, nedsalk approved these changes

2025-01-02 13:36 UTC, petertonysmith94 approved these changes

2025-01-02 14:17 UTC, nedsalk approved these changes

2025-01-02 14:39 UTC, arboleya approved these changes

2025-01-02 15:18 UTC, merged