feat: support optimistic concurrency control headers
FuelLabs/fuels-ts pull request #3462
Opened 2024-12-09 17:39 UTC by Torres-ssf

- Closes #3443

# Release notes

In this release, we:

- TBD

# Summary

```mermaid
flowchart TD
    %% Initialization
    A[Initialize LATEST_BLOCK_HEIGHT = 0] --> B[Set request header required block to be LATEST_BLOCK_HEIGHT]
    
    %% Send Request
    B --> C[Send Request]
    
    %% Response Handling
    C -->|Response: 200 OK| D[Extract CURRENT_BLOCK_HEIGHT from Response]
    C -->|Response: 412 Precondition Failed| E[Increment Retry Count]
    
    %% Update Latest Block Height
    D --> F[Is CURRENT_BLOCK_HEIGHT > LATEST_BLOCK_HEIGHT?]
    F -->|Yes| G[Update LATEST_BLOCK_HEIGHT]
    F -->|No| H[No Change]
    G --> I[Proceed with next operation/request]
    H --> I[Proceed with next operation/request]
    
    %% Handling 412 - Precondition Failed
    E -->|Retry Count < Max Retries| J(Wait and Retry)
    J --> C
    E -->|Retry Count >= Max Retries| K[Abort]
    
    %% End Conditions
    K --> O[End]
    I --> O[End]
```

# Checklist

- [ ] All **changes** are **covered** by **tests** (or not applicable)
- [ ] All **changes** are **documented** (or not applicable)
- [ ] I **reviewed** the **entire PR** myself (preferably, on GH UI)
- [ ] I **described** all **Breaking Changes** (or there's none)

2025-02-13 23:30 UTC, Torres-ssf commented
Blocked by https://github.com/FuelLabs/fuel-core/pull/2666

2025-02-17 13:52 UTC, Torres-ssf commented
Blocked by the next `fuel-core` minor [release](https://github.com/FuelLabs/fuel-core/releases), probably `0.42.0`

2025-02-17 19:55 UTC, arboleya requested changes

2025-02-17 19:55 UTC, arboleya commented on packages/account/src/providers/provider.ts
> +        this.setCurrentBlockHeight(response as { extensions: unknown });
@Torres-ssf Because the node waiting time threshold is dynamic and can be changed or disabled at any time, we must validate the response and implement the whole timing/check/retry independently.

2025-02-27 14:40 UTC, closed without merging

2025-02-27 14:40 UTC, Torres-ssf commented
Closing in favor of https://github.com/FuelLabs/fuels-ts/pull/3741