feat: Add `addContracts` to contract invocation scope
FuelLabs/fuels-ts pull request #411
Opened 2022-07-17 18:33 UTC by QuinnLee

Following the recommendation from https://github.com/FuelLabs/fuels-ts/issues/386

2022-07-17 18:34 UTC, QuinnLee commented on packages/contract/src/__test__/contract.test.ts
> +    expect(scope.transactionRequest.getContractOutputs()).toEqual([{ type: 1, inputIndex: 0 }]);
Not sure what the best way to test this was, I ended up doing this.

2022-07-18 14:32 UTC, luizstacio requested changes

2022-07-18 14:32 UTC, luizstacio commented on packages/contract/src/contracts/functions/base-invocation-scope.ts
> +  addContracts(contracts: Array<ContractIdLike> | ContractIdLike) {
- I think because of the name it should always receive an array.

2022-07-20 04:17 UTC, luizstacio approved these changes

2022-07-20 19:59 UTC, QuinnLee commented on packages/contract/src/__test__/call-test-contract/src/main.sw
> +    response + 1
decided to do so we can verify from the test

2022-07-20 20:00 UTC, QuinnLee commented on packages/contract/src/__test__/call-test-contract/src/main.sw
> +  fn call_external_foo(param: u64, contract_id: b256) -> u64 {
I was getting errors when I set `contract_id: ContractId` - I'll open an issue to investigate

2022-07-20 21:51 UTC, luizstacio approved these changes

2022-07-22 17:56 UTC, merged