doc: update parts to avoiding breaking the flow
FuelLabs/fuels-ts pull request #463
Opened 2022-08-21 18:49 UTC by luizstacio

2022-08-21 20:57 UTC, QuinnLee approved these changes

2022-08-22 14:05 UTC, LuizAsFight requested changes
just small typo

2022-08-22 14:05 UTC, LuizAsFight commented on docs/QUICKSTART.md
> +  "<replace this the contract id displayed on forc deploy>";
typo, replace to:

"replace this with the contract id displayed on forc deploy"

2022-08-22 15:22 UTC, LuizAsFight approved these changes

2022-08-22 16:48 UTC, merged