feat!: add simpler Option style
FuelLabs/fuels-ts pull request #471
Opened 2022-08-26 07:31 UTC by camsjams

Closes #470

- Adds Option support
- Adds tests for Option
- Updates Typechain types to use new Option style

2022-08-26 15:39 UTC, luizstacio requested changes
I think we should also include typechain on this change.

2022-08-26 15:39 UTC, luizstacio commented on packages/contract/src/__test__/coverage-contract/coverage-contract.test.ts
> +      .echo_option_extract_u32(INPUT_NONE)
On my opinion it should be possible to execute this `echo_option_extract_u32()`

2022-08-26 16:50 UTC, QuinnLee commented on packages/abi-coder/src/abi-coder.ts
> +      return param.type === 'enum Option'
I was trying to think of a better way to de-nest this but couldn't.  My gut tells me we should refactor `getCoder` but probably not a blocker for this pr

2022-08-30 19:55 UTC, luizstacio requested changes

2022-08-30 19:55 UTC, luizstacio commented on packages/abi-coder/src/abi-coder.ts
> +        : new EnumCoder(enumMatch.name, coders);
```suggestion
     const isOptionEnum = param.type === OPTION_CODER_TYPE;
     if (isOptionEnum) {
         return new OptionCoder(enumMatch.name, coders);
     }
     return new EnumCoder(enumMatch.name, coders);
```

2022-08-31 00:47 UTC, luizstacio approved these changes
Just one code comment.

2022-08-31 15:06 UTC, luizstacio approved these changes

2022-08-31 15:08 UTC, QuinnLee approved these changes

2022-09-01 16:15 UTC, merged