chore: relocate contract related testing
FuelLabs/fuels-ts pull request #526
Opened 2022-10-04 06:36 UTC by camsjams

Closes #492

2022-10-05 13:30 UTC, QuinnLee submitted a review, later dismissed

2022-10-05 15:49 UTC, luizstacio requested changes
Why the name gauge?

2022-10-05 15:49 UTC, luizstacio commented on packages/fuel-gauge/src/utils.ts
>  import type { BytesLike } from '@ethersproject/bytes';
We can import `BytesLike` from `fuels` and remove depedency for `@ethersproject/bytes`

2022-10-05 15:49 UTC, luizstacio commented on packages/fuel-gauge/package.json
> +    "@ethersproject/sha2": "^5.6.0",
Can we remove this dependency? By importing from `fuels`

2022-10-10 23:56 UTC, QuinnLee approved these changes

2022-10-11 14:32 UTC, luizstacio approved these changes

2022-10-11 14:32 UTC, merged