feat: automate doc generation
FuelLabs/fuels-ts pull request #533
Opened 2022-10-11 07:15 UTC by camsjams

Closes #123 

1. Added a new Workflow
2. The workflow will only fire on the Changeset branch PR
3. It will rebuild docs
4. If docs have changed, it will commit the changes to the same Changeset PR as the `github-actions[bot]` user
5. If docs have not changed, no commits will be made

I also let it run here on this PR, so it committed doc updates based on master

2022-10-13 14:21 UTC, luizstacio requested changes
Is it possible to integrate the changeset flow instead of another workflow?

2022-10-17 15:09 UTC, luizstacio requested changes

2022-10-17 15:09 UTC, luizstacio commented on package.json
> +    "changeset:publish-with-docs": "pnpm typedoc && pnpm changeset:publish",
```suggestion
    "changeset:publish-with-docs": "run-s typedoc changeset:publish",
```

2022-10-18 15:20 UTC, luizstacio approved these changes

2022-10-19 19:13 UTC, LuizAsFight approved these changes

2022-10-23 17:45 UTC, QuinnLee approved these changes

2022-10-24 14:00 UTC, merged