feat: add forc fmt check
FuelLabs/fuels-ts pull request #535
Opened 2022-10-11 18:39 UTC by camsjams

Closes https://github.com/FuelLabs/fuels-ts/issues/473

2022-10-11 19:28 UTC, QuinnLee approved these changes
looks like most of the changes are from a formatter

2022-10-11 19:40 UTC, luizstacio requested changes

2022-10-11 19:40 UTC, luizstacio commented on .github/workflows/test.yaml
> +      - name: Forc Format
We can run just `forc fmt --check` here

2022-10-11 23:11 UTC, luizstacio approved these changes

2022-10-12 21:23 UTC, LuizAsFight approved these changes

2022-10-12 21:23 UTC, merged