feat: add better documentation features and convert from Rust repo
FuelLabs/fuels-ts pull request #612
Opened 2022-11-20 21:18 UTC by camsjams

Closes #548 

## How to view these updated docs
#### 1. Basic Viev
Browse the repo on GitHub or local [using the markdown files](https://github.com/FuelLabs/fuels-ts/tree/cm/issue-548/docs/guide)

#### 2.  Recommended  View
Browse the docs [using Jekyll ](https://jekyllrb.com/docs/) (`bundle exec jekyll serve`) to see how they will appear on GitHub when deployed, which [matches current docs here](https://github.com/FuelLabs/fuels-ts)

## Notable features
The docs will always report what versions of Fuels/Sway/Fuel Core they were built with:
![image](https://user-images.githubusercontent.com/833485/202925841-40f553b0-65f5-45ac-bef8-f5cfa5ac0380.png)

New Guide section:
![image](https://user-images.githubusercontent.com/833485/202925859-c090ef47-e9eb-4138-b05b-212f8e658d9f.png)

Embedded code using real code from library and unit tests:
![image](https://user-images.githubusercontent.com/833485/202925879-de0a8df1-f00b-490d-98ee-e4f8413cedd5.png)

## Notes
- The format and chapters added are sourced from the [Rust SDK Docs](https://fuellabs.github.io/fuels-rs/v0.31.1/) and adjusted as needed
- 99% of code examples are sourced from unit tested code, this took a while :sweat: (see code snippets in action [right here](https://github.com/FuelLabs/fuels-ts/blob/cm/issue-548/docs/_guide/types/address.md?plain=1#L11) for example)
- Some docs were excluded from the docs as the Rust concepts didn't apply
- I added some new Docs and code snippets as needed
- I added the new AbiCoder for B512 as it was needed for an example :sweat_smile: 
- I ended up [making a new plugin](https://xkcd.com/927/) for Typedoc :sweat_smile:  that [copies the `docs/_guide` source folder into `docs/guide`](https://github.com/FuelLabs/fuels-ts/tree/cm/issue-548/scripts/typedoc-plugin-guide-builder) and also pulls in code samples from repo as needed using syntaxt inspired by other Doc tools in other languages (and the [Typedoc code block](https://www.npmjs.com/package/@knodes/typedoc-plugin-code-blocks) plugin which wasn't working well enough for our needs). 
- the [Jekyll data variables defined here](https://github.com/FuelLabs/fuels-ts/blob/cm/issue-548/docs/_data/versions.yml) are pulling in [environment vars passed here ](https://github.com/FuelLabs/fuels-ts/blob/cm/issue-548/scripts/changeset-publish-with-docs.ts#L8)which were [originally parsed out in this code here](https://github.com/FuelLabs/fuels-ts/blob/cm/issue-548/.github/workflows/release.yaml#L28-L30)
- Finally, this is not exhaustive, but is exhausting. We should get this proofread and code checked and then plan to add more pages in new PRs, and also aim to get this new version out to prod ASAP

2022-11-20 23:07 UTC, jacobrosenthal commented on README.md
> +We recommend starting with the [Quickstart](https://fuellabs.github.io/fuel-docs/master/developer-quickstart.htmll) to speed-up and build your first DApp using Fuel.
```suggestion
We recommend starting with the [Quickstart](https://fuellabs.github.io/fuel-docs/master/developer-quickstart.html) to speed-up and build your first DApp using Fuel.
```

2022-11-20 23:08 UTC, jacobrosenthal commented on README.md
> +- [Quickstart](https://fuellabs.github.io/fuel-docs/master/developer-quickstart.htmll)
```suggestion
- [Quickstart](https://fuellabs.github.io/fuel-docs/master/developer-quickstart.html)
```

2022-11-22 16:04 UTC, arboleya requested changes

2022-11-22 16:04 UTC, arboleya commented on packages/abi-coder/src/coders/b512.ts
> +export default class B512Coder extends Coder<string, string> {
If I understand it correctly, the tests for all coders are condensed in a single<sup>(*)</sup> file, right? Please add a new one for `b512`.
 - `src/coders/coders.test.ts`

> _<sup>(*)</sup> Although I find it very confusing to have tests selectively grouped in any way that's not side-by-side with their source counterpart, this is how it seems to have been done in this case._

2022-11-23 00:53 UTC, digorithm commented on docs/_guide/contracts-in-action/call-params.md
> +Here we set call params alongside transaction params:
Suggestion: this section (`Call parameters`) comes before the section `Tx Params`, but mentions transactions params; users might not know what it means. Can we have `Tx Params` (which could be renamed to `Transaction parameters` IMO) before `Call parameters`?

2022-11-23 00:55 UTC, digorithm commented on docs/_guide/contracts-in-action/call-params.md
> +Here we set call params as part of a Multicall
Similar situation here: mentioning something that hasn't been introduced yet. But I think in this case having a link in `Multicall` to its appropriate section would be perfectly fine!

2022-11-23 00:56 UTC, digorithm commented on docs/_guide/contracts-in-action/cost-estimation.md
> +With with the function `getTransactionCost` provided by the `provider`, you can get a cost estimation for a specific call. The return type, `TransactionCost`, is an object that contains relevant info
```suggestion
With the function `getTransactionCost` provided by the `provider`, you can get a cost estimation for a specific call. The return type, `TransactionCost`, is an object that contains relevant information for the estimation:
```

2022-11-23 01:06 UTC, digorithm commented on docs/_guide/contracts-in-action/multicalls.md
> +### Different cCntracts in multicalls
```suggestion
### Different contracts in multicalls
```

2022-11-23 01:07 UTC, digorithm commented on docs/guide/contracts-in-action/other-contracts.md
> +title: "Other Contracts"
Can we rename it from `"Other Contracts"` to `"Calling external contracts"`?

2022-11-23 01:09 UTC, digorithm commented on docs/guide/contracts-in-action/read-only.md
> +title: "Read Only"
Let's rename just this title here to `Read-only calls`, which is in fact the header's title of this file, but on the side bar it only shows `"Read Only"`.

2022-11-23 01:19 UTC, digorithm commented on docs/_guide/contracts-in-action/variable-outputs.md
> +In some cases, you might want to send funds to the output of a transaction. Sway has a specific method for that: `transfer_to_address`(coins, asset_id, recipient)`. So, if you have a contract that do
```suggestion
In some cases, you might want to send funds to the output of a transaction. Sway has a specific method for that: `transfer_to_address(coins, asset_id, recipient)`. So, if you have a contract that does something like this:
```

2022-11-23 01:32 UTC, digorithm commented on docs/guide/wallets/encrypting-and-storing.md
> +title: "Encrypting And Storing"
```suggestion
title: "Encrypting and Storing Wallets"
```

2022-11-23 01:36 UTC, digorithm commented on docs/_guide/wallets/encrypting-and-storing.md
> +[@code:typescript](./packages/wallet-manager/src/wallet-manager.test.ts#typedoc:wallet-manager-create)
Is this related to storing/retrieving wallets to/from disk? I'm not sure how the support for these disk-stored JSON-encrypted wallets is at the moment in the TS SDK, and this example seems not to be doing anything related to it 🤔

2022-11-23 01:40 UTC, digorithm commented on docs/guide/predicates/send-spend-predicate.md
> +title: "Send Spend Predicate"
```suggestion
title: "Send and spend funds from predicates"
```

2022-11-23 16:21 UTC, QuinnLee submitted a review, later dismissed
I dont have new comments, this LGTM!

2022-11-24 01:48 UTC, digorithm commented
>I ended up [making a new plugin](https://xkcd.com/927/) for Typedoc 😅 that [copies the docs/_guide source folder into docs/guide](https://github.com/FuelLabs/fuels-ts/tree/cm/issue-548/scripts/typedoc-plugin-guide-builder) and also pulls in code samples from repo as needed using syntaxt inspired by other Doc tools in other languages (and the [Typedoc code block](https://www.npmjs.com/package/@knodes/typedoc-plugin-code-blocks) plugin which wasn't working well enough for our needs).

@camsjams I love this! One upgrade we could do to it is to configure page order in the navigation bar. Could you work on this at some point? We could add the order to the filename itself (`00-first-page.md`) and then the plugin's code would strip `00-` off of it and use it to pass this value to `nav_order`.

2022-11-24 02:19 UTC, digorithm submitted a review, later dismissed
Made some changes and I think we're at a nice place for a first release. Still, lots of work to be done. 

Great job, @camsjams, for getting the ball rolling. I love the compile-checks on the docs' code!

2022-11-24 02:37 UTC, QuinnLee submitted a review, later dismissed

2022-11-24 18:55 UTC, digorithm submitted a review, later dismissed

2022-11-24 20:19 UTC, QuinnLee approved these changes

2022-11-25 16:00 UTC, arboleya requested changes
Outstanding job! 🤘 
This certainly puts us in the right direction.

I left a couple of mentions here and there, and I'd like to suggest we stop using automatic sorting (_alphabetical_) for the sidebar menu.

I'm not sure exactly what would be the best order, but here's a first idea (check the image on the **_right_**). Maybe someone else can chime in on this one.

Feel free to push things into new issues if you prefer.

<details>
  <summary>Before</summary>

```
1. Home

2. Guide
  Types
  Address
  Arrays
  Asset Id
  Bech32
  Bits256
  Bytes32
  Contract Id
  Conversion
  Enums And Options
  String
  Structs
  Using Generated Types
  Vectors

3. Contracts
  Call Parameters
  Calling External Contracts
  Calls With Different Wallets
  Cost Estimation
  Deploying Contracts
  Generate Contract Types From Abi
  Interacting With Contracts
  Logs
  Multicalls
  Read Only Calls
  The Fuelvm Binary File
  The Json Abi File
  Transaction Parameters
  Variable Outputs

4. Providers
  Connecting To An External Node
  Connection
  Querying The Chain

5. Cookbook
  Deposit And Withdraw
  Transfer All Assets

6. Testing
  Testing With Jest

7. Predicates
  Send And Spend Funds From Predicates

8. Wallets
  Access
  Checking Balances And Coins
  Encrypting And Storing Wallets
  Mnemonic Wallet
  Private Keys
  Signing
  Test Wallets
  Transferring Assets

9. Quickstart
```

</details>

<details>
  <summary>After</summary>

```
1. Home

2. Quickstart

3. Guide
  Types
  Address
  Arrays
  Asset Id
  Bech32
  Bits256
  Bytes32
  Contract Id
  Conversion
  Enums And Options
  String
  Structs
  Vectors

4. ABI Typegen
  Generating Types
  Using Generated Types

5. Wallets
  Access
  Checking Balances And Coins
  Encrypting And Storing Wallets
  Mnemonic Wallet
  Private Keys
  Signing
  Test Wallets
  Transferring Assets

6. Providers
  Connection
  Connecting To An External Node
  Querying The Chain

7. Contracts
  Interacting With Contracts
  Read Only Calls
  Multicalls
  Cost Estimation
  Transaction Parameters
  Call Parameters
  Calling External Contracts
  Calls With Different Wallets
  Logs
  Variable Outputs
  The Fuelvm Binary File
  Deploying Contracts

8. Cookbook
  Deposit And Withdraw
  Transfer All Assets

9. Predicates
  Send And Spend Funds From Predicates

10. Testing
  Testing With Jest
```
</details>

![sorting](https://user-images.githubusercontent.com/26660/204019118-7b898a59-9edb-4308-bac1-0c3535c7de43.png)

2022-11-25 16:35 UTC, digorithm commented
I'm all for dropping the alphabetical sorting! I even mentioned it here https://github.com/FuelLabs/fuels-ts/pull/612#issuecomment-1325845853. 

Right now, it's tricky because when you edit the source and run `typedoc`, the ordering will go back to alphabetical. That's why I suggested that solution in the comment above!

2022-11-25 16:42 UTC, digorithm commented on docs/_guide/index.md
> +# The Fuel TypeScript SDK Guide
100% agreed. Though I have no idea how/where to change this, so feel free to make this change (or @camsjams).

2022-11-25 16:43 UTC, digorithm commented on docs/guide/cookbook/deposit-and-withdraw.md
> +{{#include ../../../examples/cookbook/src/lib.rs:liquidity_abigen}}
Ah, this seems to be a copy-and-paste from the Rust docs so that we can, eventually, update it with the equivalent TypeScript examples.

2022-11-30 23:34 UTC, digorithm approved these changes
Alright y'all, let's get this out. 

It's looking pretty solid; lots to improve but we got most of it good enough for a first release.

2022-11-30 23:41 UTC, QuinnLee approved these changes

2022-12-01 09:46 UTC, arboleya approved these changes

2022-12-01 18:30 UTC, merged