fix: remove addCoins, addCoin and Run `pnpm run docs`
FuelLabs/fuels-ts pull request #613
Opened 2022-11-21 06:48 UTC by QuinnLee

2022-11-21 16:58 UTC, luizstacio requested changes

2022-11-21 16:58 UTC, luizstacio commented on packages/providers/src/transaction-request/transaction-request.ts
> -  /**
I think we can remove this import from Coin also.

2022-11-24 08:44 UTC, luizstacio approved these changes

2022-11-24 10:59 UTC, arboleya approved these changes

2022-11-25 16:46 UTC, merged