feat: expose decoded transaction in fetch method
FuelLabs/fuels-ts pull request #618
Opened 2022-11-24 02:32 UTC by LuizAsFight

`TransactionResponse.#fetch` now includes the decoded transaction in response

Closes #617

2022-11-24 03:46 UTC, QuinnLee approved these changes

2022-11-24 08:51 UTC, luizstacio requested changes

2022-11-24 08:51 UTC, luizstacio commented on packages/providers/src/transaction-response/transaction-response.ts
> +    const { transaction: gqlTransaction } =
```suggestion
    const { transaction: transactionWithReceipts } =
```

2022-11-24 11:04 UTC, arboleya requested changes
Could we have a test validating the changes this PR introduces?

2022-11-25 22:16 UTC, QuinnLee approved these changes

2022-11-26 20:37 UTC, luizstacio approved these changes

2022-11-28 10:09 UTC, arboleya approved these changes

2022-11-28 10:09 UTC, merged