fix: regenerate docs + fix build version tooling
FuelLabs/fuels-ts pull request #639
Opened 2022-12-02 06:36 UTC by camsjams

2022-12-03 11:46 UTC, arboleya requested changes

2022-12-03 11:46 UTC, arboleya commented on .github/workflows/release.yaml
> +          echo "BUILD_VERSION=$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' packages/fuels/package.json)" >> $GITHUB_ENV
Using a similar approach for all regexes may improve clarity and readability.

Unless I'm missing something else.

```console
$ sed 's/.*"version": "\(.*\)".*/\1/;t;d' package.json
0.22.2
$ sed 's/.*"forcVersion": "\(.*\)".*/\1/;t;d' forc.json
0.30.0
$ sed 's/.*fuel-core:v\(.*\).*/\1/;t;d' Dockerfile
0.14.0
```

2022-12-05 09:38 UTC, arboleya approved these changes

2022-12-05 16:44 UTC, luizstacio approved these changes

2022-12-05 17:03 UTC, merged