feat: add `isB256` helper to Address
FuelLabs/fuels-ts pull request #645
Opened 2022-12-06 06:41 UTC by camsjams

Closes #626

2022-12-06 09:16 UTC, arboleya requested changes

2022-12-06 09:16 UTC, arboleya commented on packages/address/src/address.test.ts
> +  });
Duplicated test case.

```suggestion
```

2022-12-07 04:23 UTC, LuizAsFight approved these changes

2022-12-07 10:15 UTC, arboleya approved these changes

2022-12-07 10:15 UTC, merged