feat: add tests for auth functions
FuelLabs/fuels-ts pull request #664
Opened 2022-12-14 08:33 UTC by camsjams

Using same test as https://github.com/FuelLabs/fuels-rs/blob/master/packages/fuels/tests/contracts/auth_testing_contract/src/main.sw

2022-12-14 11:07 UTC, arboleya requested changes

2022-12-14 11:07 UTC, arboleya commented on packages/fuel-gauge/src/auth-testing.test.ts
> +    }
Not sure what's going on here but:
 1. Throwing inside the `try` block looks like a mistake
 2. All assertions must be outside `try/catch` blocks to ensure they always run

However, I think we could `expect(...).toThrow()` in this case:

```suggestion
    const wallet = getWallet();
    expect(() => {
      await contractInstance.functions.check_msg_sender({ value: wallet.address.toB256() }).get();
    }).toThrow();
```

2022-12-14 11:07 UTC, arboleya commented on packages/fuel-gauge/src/auth-testing.test.ts
> +    }
Here as well, shouldn't it be like this?

```suggestion
    const wallet = getWallet();
    expect(() => {
      await contractInstance.functions
          .check_msg_sender({ value: wallet.address.toB256().replace('x', 'y') })
          .call();
    }).toThrow()
```

2022-12-14 18:26 UTC, Dhaiwat10 approved these changes
@camsjams if you don't mind, I was wondering what exactly is the purpose of the `fuel-gauge` package and the tests that we are adding in this PR? Are these tests supposed to test if the SDK can correctly handle some auth-related Sway standard library and its responses? Just trying to gather some context here. 😅

2022-12-15 09:40 UTC, arboleya approved these changes

2022-12-15 15:06 UTC, Dhaiwat10 approved these changes

2022-12-15 15:06 UTC, merged