docs: Add 'deposit and withdraw' guide to cookbook
FuelLabs/fuels-ts pull request #707
Opened 2022-12-23 17:29 UTC by Dhaiwat10

- This PR adds a TS SDK counterpart of the [deposit and withdraw guide in the Rust SDK cookbook](https://fuellabs.github.io/fuels-rs/v0.33.0/cookbook/deposit-and-withdraw.html).

- This PR is _related_ to #629 but does _not_ close it since we can still add more guides to the cookbook.

2022-12-30 18:15 UTC, arboleya requested changes

2023-01-03 09:46 UTC, arboleya approved these changes

2023-01-04 17:32 UTC, arboleya commented on packages/fuel-gauge/test-projects/liquidity-pool/Forc.toml
> +name = "liquidity-pool"
Good one. These can also be trimmed down, then.

https://github.com/FuelLabs/fuels-ts/blob/d0c74cd59f249ce1bdf113ce6f1744dcf48fc3e7/packages/fuel-gauge/test-projects/collision_in_fn_names/Forc.toml#L1-L5

https://github.com/FuelLabs/fuels-ts/blob/d0c74cd59f249ce1bdf113ce6f1744dcf48fc3e7/packages/fuel-gauge/test-projects/token_contract/Forc.toml#L1-L5

https://github.com/FuelLabs/fuels-ts/blob/d0c74cd59f249ce1bdf113ce6f1744dcf48fc3e7/packages/fuel-gauge/test-projects/token_abi/Forc.toml#L1-L5

2023-01-04 19:35 UTC, Dhaiwat10 commented on packages/fuel-gauge/test-projects/token_contract/src/main.sw
> +// #endregion
@camsjams not sure if I follow you here. The `token_contract` folder does have a [`Forc.toml`](https://github.com/FuelLabs/fuels-ts/blob/dp/issue-629/packages/fuel-gauge/test-projects/token_contract/Forc.toml)

2023-01-05 08:45 UTC, arboleya approved these changes

2023-01-05 18:41 UTC, digorithm approved these changes
Excellent work @Dhaiwat10!

2023-01-09 16:42 UTC, digorithm approved these changes
:shipit:

2023-01-09 17:13 UTC, merged