feat: add main arg support to Predicates
FuelLabs/fuels-ts pull request #746
Opened 2023-01-20 01:01 UTC by camsjams

closes #700

2023-01-20 16:58 UTC, Dhaiwat10 approved these changes
🫡

2023-01-20 18:31 UTC, arboleya requested changes
Looking good overall. 👌 

I still have specific concerns with parameter type _overloading_ and the trade-off between:
 - `flexibility` _(not always essential)_
 - `simplicity` _(mostly desirable)_

My suggestions are based on the latter. You're free to dismiss them.

I'd love to understand the reasoning behind the decision.

Thanks.

2023-01-20 18:31 UTC, arboleya commented on packages/predicate/src/predicate.ts
> +    }
If we'd stop overloading the `types` parameter by accepting only `JsonAbi`:

```suggestion
    const abiInterface = new Interface(types);
    const mainFunction = abiInterface.fragments.find(({ name }) => name === 'main');
    
    if (mainFunction !== undefined) {
      this.types = mainFunction.inputs;
    } else {
      logger.throwArgumentError(
        'Cannot use ABI without "main" function',
        'Function fragments',
        abiInterface.fragments,
      );
    }
```

2023-01-30 16:17 UTC, arboleya requested changes

2023-01-30 16:17 UTC, arboleya commented on docs/_guide/predicates/index.md
> +You can still create a `Predicate` in the same way as above, but you can pass in a `JsonAbi | Interface` using the JSON generated from `forc`.
Now it's `JsonAbi`, the mention of `Interface` can be removed.
```suggestion
You can still create a `Predicate` in the same way as above, but you can pass in a `JsonAbi` using the JSON generated from `forc`.
```

2023-01-30 16:17 UTC, arboleya commented on packages/fuel-gauge/src/predicate.test.ts
> +import { Address, NativeAssetId, bn, toHex, toNumber, Provider, Predicate, Interface } from 'fuels';
`Interface` isn't used and can be removed.

```suggestion
import { Address, NativeAssetId, bn, toHex, toNumber, Provider, Predicate } from 'fuels';
```

2023-01-30 20:06 UTC, luizstacio requested changes

2023-01-30 20:06 UTC, luizstacio commented on packages/predicate/src/predicate.ts
> +      const abiInterface = new Interface(types as JsonAbi);
It is missing the assignment to variable `this.interface`.
```suggestion
           this. interface = new Interface(types as JsonAbi);
```

2023-01-30 20:06 UTC, luizstacio commented on packages/fuel-gauge/src/predicate.test.ts
> +    await wallet.provider.submitSpendPredicate(
We should add a type optional argument here to inform the Validation types. It will help to generate better types after.

2023-01-31 21:56 UTC, LuizAsFight approved these changes

2023-02-01 14:55 UTC, arboleya commented on packages/providers/src/provider.ts
> +      encoded = abiCoder.encode(predicate.types, predicateData as InputValue[]);
Shouldn't this be `InputValue<T>[]`? _(see method signature on line `735`)._

Does it make any difference?

```suggestion
      encoded = abiCoder.encode(predicate.types, predicateData as InputValue<T>[]);
```

2023-02-01 14:58 UTC, arboleya approved these changes
Approving as is, but I've left one last comment about Generics.

2023-02-01 16:17 UTC, luizstacio approved these changes

2023-02-01 18:50 UTC, arboleya commented on packages/providers/src/provider.ts
> +      encoded = abiCoder.encode(predicate.types, predicateData as InputValue[]);
Oh, my bad. You are right.

It looks like `values: InputValue[]` is expected.


https://github.com/FuelLabs/fuels-ts/blob/f521146c328a7fb2c98679ec3f0c9aa6df2f684f/packages/abi-coder/src/abi-coder.ts#L122

2023-02-01 18:50 UTC, merged