chore: upgrade node to LTS
FuelLabs/fuels-ts pull request #796
Opened 2023-02-20 15:22 UTC by Torres-ssf

- Close #795

2023-02-20 21:20 UTC, arboleya requested changes
Please, also address the removal of the obsolete dependency and the related _[soon to be broken]_ imports:
 - https://github.com/FuelLabs/fuels-ts/pull/767#discussion_r1112294121

2023-02-21 00:52 UTC, Torres-ssf commented
About the comment on [#767](https://github.com/FuelLabs/fuels-ts/pull/767#discussion_r1112294121) 

Not sure if it was just to move `node-fetch` dependency to `devDependencies` on the `providers` workspace or just to remove its import on providers test file

2023-02-21 10:50 UTC, Torres-ssf commented on packages/providers/package.json
> +    "node-fetch": "^2.6.7"
Thanks mate

2023-02-21 11:08 UTC, arboleya approved these changes

2023-02-21 15:38 UTC, luizstacio approved these changes

2023-02-21 16:12 UTC, merged