Torres/docs/add docs for getting contract balance
FuelLabs/fuels-ts pull request #960
Opened 2023-04-30 22:10 UTC by Torres-ssf

2023-05-01 09:53 UTC, arboleya reviewed
Would it be useful to showcase the Sway contract that the snippet example interacts with to give users the full picture of what the call below is doing?

```ts
const scope = contract.functions.return_context_amount().callParams({
  forward: [amountToForward, NativeAssetId],
});
```

I did something similar here:

 - https://fuellabs.github.io/fuels-ts/guide/abi-typegen/using-generated-types.html#using-generated-predicate-types

I'm not sure if, in this case, it'd add noise to the `getBalance` stuff, but in general, I have the feeling that it's good to have a full understanding of the examples.

See if you think.

2023-05-03 11:58 UTC, Dhaiwat10 submitted a review, later dismissed

2023-05-05 10:10 UTC, danielbate approved these changes

2023-05-05 10:23 UTC, arboleya requested changes
Very clean and straight to the point. ❤️ 

Left some trivial tyop corrections and suggestions.

2023-05-05 10:23 UTC, arboleya commented on apps/docs/src/guide/contracts/contract-balance.md
> +1. `amount_to_transfer`: The amount that is being transfered.
```suggestion
1. `amount_to_transfer`: The amount that is being transferred.
```

2023-05-05 10:23 UTC, arboleya commented on apps/docs/src/guide/contracts/contract-balance.md
> +3. `recipient`: The address from the receive's wallet.
```suggestion
3. `recipient`: The address from the receiver's wallet.
```

2023-05-05 10:23 UTC, arboleya commented on apps/docs/src/guide/contracts/contract-balance.md
> +The `transfer` function calls the built-in Sway function `transfer_to_address`, which does exactly what the name suggests.
```suggestion
The `transfer` function calls the built-in Sway function `transfer_to_address`, which does precisely what the name suggests.
```

2023-05-05 10:23 UTC, arboleya commented on apps/docs/src/guide/contracts/contract-balance.md
> +Let's execute this contract and use the `getBalance` method to validate the remaining asset amount that the contract has left to spend.
```suggestion
Let's execute this contract and use the `getBalance` method to validate the remaining asset amount the contract has left to spend.
```

2023-05-05 10:23 UTC, arboleya commented on apps/docs/src/guide/contracts/contract-balance.md
> +Finally we use the `getBalance` method to confirm that the contract balance is precisely the total forwarded amount minus the transferred amount.
```suggestion
Finally, we use the `getBalance` method to confirm that the contract balance is precisely the total forwarded amount minus the transferred amount.
```

2023-05-05 10:23 UTC, arboleya commented on apps/docs/src/guide/contracts/contract-balance.md
> +It is important to note that this method returns the total available contract balance, regardless of how many times assets have been sent or spent on costly operations.
```suggestion
It is important to note that this method returns the total available contract balance, regardless of how often assets have been sent or spent on costly operations.
```

2023-05-05 11:55 UTC, Torres-ssf commented on apps/docs/src/guide/contracts/contract-balance.md
> +1. `amount_to_transfer`: The amount that is being transfered.
Good catch @arboleya

2023-05-05 12:24 UTC, arboleya approved these changes

2023-05-05 17:20 UTC, Dhaiwat10 approved these changes

2023-05-05 17:20 UTC, merged